jacktrip/jacktrip

jacktrip/src/Settings.cpp

this fixes a couple of typos (*defaul* rather than *default*, and uses consistent display of defaults (`default: foo` rather than `defaults to foo` vs `default foo` vs `default is foo`)
also: since jacktrip doesn't have a manpage, the Debian package automatically generates one from the output of `-h` and `-v`.
This would work nicely if jacktrip didn't overzealously format the output with separator lines (`------------` and `===========`).
The pull requests removes those lines, as I believe that the output is structured enough to be easily readable (there are big HEADINGS that separate all the paragraphs)

fixes for help printout

---

src/AudioInterface.h
src/JackTrip.cpp
src/JackTrip.h
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/Settings.cpp
src/Settings.h
src/jacktrip_globals.h

Allow the selection of `device_id` when using `rtaudio` instead of relying on the default.
Should be used in conjunction with an `rtaudio` version that supports outputting the device ID on `audioprobe`

Select device ID when using rtaudio

---

src/JackTrip.cpp

This fix sets the jack clientname when mPeerAddress is not set (in server mode)

fix to set clientname when in server mode

---

src/DataProtocol.h
src/JackTrip.cpp
src/JackTrip.h
src/JackTripWorker.cpp
src/RingBuffer.cpp
src/RingBuffer.h
src/Settings.cpp
src/Settings.h
src/UdpDataProtocol.cpp
src/UdpDataProtocol.h
src/UdpMasterListener.h

Reporting can be turn on with `--iostat` option. It prints collected counters regularly with a specified time interval in stdout or in a separate file (with `--iostatlog`), a record per line. The format is
2020-06-07T22:37:53 172.16.101.115 send: 0/0 recv: 152/3 prot: 153/0/4 tot: 7507 skew: 0
It shows
- send ring buffer underruns / overflows
- recv ring buffer underruns / overflows
- udp packets counters: lost / out-of-order / restored-from-redundant-packets
- total packet counter
- cumulative clock skew estimation (in packets) calculated as recv_underruns - recv_overflows - (lost - restored).
To detect the skew reliably the log should be long enough (at least 30 minutes).
Each UDP protocol instance is reported independently (labeled with the corresponding IP address).

Add optional IO statistics reporting

---

INSTALL_meson.md
meson.build

This adds meson as alternative to building jacktrip with qmake. It's tested with Fedora Linux. Other Linux distributions should just work. I would be very interested in the experience under Windows and MacOS.
Meson should be installed by default with recent Linux distributions. For Windows and Mac you can look [here](https://mesonbuild.com/Getting-meson.html).
Following commands build jacktrip (debug and unoptimized by default):
cd jacktrip
meson builddir
ninja -C builddir
To install in default location (e.g. /usr/local/bin):
ninja -C builddir install

Meson build support

---

.travis.yml
src/RingBuffer.h
src/build
src/jacktrip.pro

Basic Travis Continuous Integration support. Adds a `.travis.yml` to the repo and fixes a few things that were preventing it from compiling on Travis' Linux VM.
Currently this simply compiles jacktrip on Linux + Mac to ensure that it compiles on both. A test suite + Windows + installer generation can be added on top of this foundation.  
To close the loop, Travis also needs to be added to the jacktrip repo, which needs to be done by someone with read/write permission to the repo (I can do this if you add me). 
Note: please use "squash and merge" when merging as there are a lot of pointless commits to test Travis functionality; squashing will reduce these down to a single commit.

first pass: Travis integration

---

src/UdpDataProtocol.cpp

Removed an extra _ in a couple of defines.

Fix OSX defines in UdpDataProtocol

---

README.md

Removed extra space after CCRMA link, following the formatting of the other links.

Tiny formatting fix

---

src/UdpHubListener.cpp
src/jacktrip_globals.h

TcpServer was not checking for pending connections before waiting to receive new ones. This was causing it to fail when more than 1 client connected to a hub server at the same time.
Also bumping pthreads limit -- this was tested at scale of 500 with no issues

Fix for hubserver failure with concurrent connections

---

.gitignore
INSTALL.txt
src/build

Currently running the `./build` script generates artifacts in the `src` directory, being intermingled with source files and showing up as uncommitted changes in the git repository.
In this PR I propose to create the `build` subdirectory, add its contents to `.gitignore` and change the build script to output files there. 
With my limited experience I'm not sure if this is the best approach, I'm looking forward to getting some feedback on this!

build in a subdirectory

---

INSTALL.txt
INSTALL_meson.md
src/build

Updated build script to select QT5 build tools when 4 and 5 are installed. Resolves #105

Set QT5 dependency in build script

---

INSTALL.txt
INSTALL_meson.md
src/build

Reverts jacktrip/jacktrip#108
Creates a new dependency without which the build fails
Reports are "qtchooser: command not found"

Revert "Set QT5 dependency in build script"

---

src/build
src/jacktrip.pro

- This forwards all parameters of the build script to qmake
- './build PREFIX=/usr; make install' installs jacktrip in /usr/bin
- './build; make install' installs jacktrip in /usr/local/bin, so it doesn't conflict with a packaged installation of jacktrip

Define PREFIX variable for installation path (Defaults to /usr/local)

---

src/Effects.h
src/Settings.cpp

Bugfix PR for commit Jos (#135): 
Aaron: 
- allocate Faust audio effects during mJackTrip client creation only (not server).
- do not deallocate effects in Effects.cpp because AudioInterface.cpp is doing it.
- return 0 upon successful parsing of --assumednumclients
- reduce compiler warnings
Anton:
- load allocated audio effects during mJackTrip client creation only (not server).
jos: 
- add explanatory comments
- reduce compiler warnings

jos branch Aaron/Anton/JOS bugfix PR

---

src/Settings.cpp

Move closing '}' for mJackTrip client creation where it belongs in Settings.cpp

correct location of closing curly brace on mJackTrip client creation

---

src/JackTrip.h
src/Settings.cpp

following suggestion from Julius Smith:
```
While we are considering more informative terms, how about changing 
-s, --server                             Run in Server Mode
-c, --client <peer_hostname_or_IP_num>   Run in Client Mode
-S, --jacktripserver                     Run in Hub Server Mode
-C, --pingtoserver <peer_name_or_IP>     Run in Hub Client Mode
to (assuming my evolving understanding is correct)
-s, --server                             Run in P2P Server Mode
-c, --client <peer_hostname_or_IP_num>   Run in P2P Client Mode
-S, --jacktripserver                     Run in Hub Server Mode
-C, --pingtoserver <peer_name_or_IP>     Run in Hub Client Mode
I see that a right-click lookup of P2P on Mac OS yields "peer-to-peer", so probably no need to define/expand it.
```

add P2P to info

---

src/Settings.cpp

The short form of the IO stat options weren't configured to take a parameter, so segfaulted when used.

Fix short form IO stat options

---

src/JMess.cpp
src/JackAudioInterface.cpp
src/JackTrip.cpp
src/JackTrip.h
src/RingBuffer.cpp
src/UdpDataProtocol.cpp

Notify the JackTrip networking thread rather than throwing an error when the Jack Server is shutdown. (Allows the program to either exit gracefully, or simply show an error when run with a GUI.)
Also fix the handling of jack client names with unicode characters in JMess. (Use toUtf8 instead of toLatin1.)

Shutdown gracefully when Jack Server stops

---

src/AudioInterface.cpp
src/AudioInterface.h
src/AudioTester.cpp
src/AudioTester.h
src/JackTrip.cpp
src/JackTrip.h
src/Settings.cpp
src/Settings.h
src/jacktrip.pro

Feature pull-request for the dev branch:
--examine-audio-delay (-x)
for measuring audio latency to sample accuracy,
and computing its long-term mean and standard-deviation

--examine-audio-delay (-x) feature for measuring audio latency to sample accuracy

---

src/AudioInterface.cpp

This is not needed when there is a limiter, but since limiters are off by default (I think an outgoing limiter should be ON by default in every audio channel unless -b 32 is in use), it makes sense to at least hard-clip instead of wrap around in two's complement.  Wrap-around is much noisier than clipping.
There was another pull request about this, which I approved subject to comments, but it never got completed, so I wrote this based on that discussion.

Hard-clip outgoing conversion from floats to fixed-point

---

faust-src/Makefile
faust-src/Makefile.headers
faust-src/compressordsp.dsp
faust-src/tests/compressor-limiter-test.dsp
faust-src/tests/compressor2dsp.dsp
src/compressordsp.h
src/freeverbdsp.h
src/freeverbmonodsp.h
src/limiterdsp.h
src/zitarevdsp.h
src/zitarevmonodsp.h

Minor Faust-related changes.
Update to latest Faust compiler (v2.28.5 on branch master-dev).
Changes can only affect limiter, compressor, or reverb, all of which are off by default.

Minor Faust-related changes

---

documentation/documentation.cpp

Jackosx.com link does not work anymore. We could either link to the JACK downloads page or directly to the JACK2 binary for Mac OS X.

Update download link in docs

---

src/JackAudioInterface.cpp

Setting the jack server name null may be unintended here.

Don't nullptr jack server name when creating jack client

---

src/AudioInterface.cpp
src/AudioTester.cpp
src/AudioTester.h
src/Effects.h
src/Settings.cpp

Generalize --examine-audio-delay (-x) to support normal JackTrip usage in audio channels below the last, which is dedicated to latency testing, and need not be hooked up to JACK.  Thus, we can have continuous silent latency testing on an extra audio channel in parallel with normal JackTrip usage.

 generalize --examine-audio-delay (-x) to allow normal jacktrip usage in audio channels below test channel

---

src/Settings.cpp

Print options-related error message after usage so that it can be seen on the same screen.
Minor additional clarity improvements.

improve clarity of options-related printout

---

src/AudioTester.cpp
src/AudioTester.h
src/Settings.cpp

This small PR supports "jacktrip -x help" to explain what is measured and how it is displayed.  Additionally, a small refinement was made to the algorithm used to detect return impulses.  Minor string formatting improvements included.

add help to --examine-audio-delay (-x) and slightly refine algorithm for return impulse detection

---

src/AudioInterface.cpp
src/AudioTester.cpp
src/AudioTester.h

This completes support of audio latency testing in a (silent) highest-numbered channel while using the lower-numbered channels normally.

support audio latency testing in silent channel during normal operation

---

src/AudioTester.h

The histogram bins did not quite match the range that was being printed out for them.

revise quantization of -x audio latency histogram bins

---

src/Effects.h
src/Settings.cpp

This is the PR for turning on the limiter by default modified to turn it OFF instead.  Thus, it is a no-op, but it makes it more clear that the outgoing limiter is intentionally being turned off, overriding the recommended default in Effects.h.  It also saves the general code improvements associated with the deleted PR wanting to turn it on, and makes it easier to turn it back on, should that ever be desired.

outgoing limiter more clearly turned off by default

---

.github/workflows/jacktrip.yml

This PR adds builds using GitHub Actions on Linux and macOS. The build artifacts are uploaded to GitHub Actions for introspection.
This PR includes:
- building JackTrip on Linux
- building JackTrip on macOS
- uploading build artifacts to GitHub Actions (expire after 30 days, can be adjusted)
This PR does _not_ include:
- building static Qt on macOS for making distributable binaries
- caching (should be definitely implemented especially if static qt build will be added)
- automatic deployment of tagged builds to github releases
- version numbers in the artifact name
- tests
I don't think GitHub Actions will run until this PR is merged. You can see it running on my fork: https://github.com/dyfer/jacktrip/actions/runs/488972949

Add GitHub Actions

---

.clang-format
src/CompressorPresets.h
src/UdpDataProtocol.cpp

I've turned clang-format off for two bigger comments. The rest looked good to me. This doesn't include the reformatting of the codebase. So when we use clang-format, the code will continuously be reformatted as we push changes.

Turn on clang-format comment reflow

---

src/UdpHubListener.cpp

Now that the port is only being read as a 16 bit integer by the hub server, the requested remote client name isn't being read properly. We need to discard the two bytes that come before it.

Fix regression in remote client name handling

---

.github/workflows/jacktrip.yml

This PR fixes Windows builds in GHA.
Changes:
- Windows image set to a particular version, so it doesn't change by itself 
- I'm not set on this, but this is consistent with current configuration on Linux and macOS
- uses mingw 8.1
- uses jack from chocolatey (as before) 
- this is Jack 1.9.11, so before we consider using these builds for deployment this should probably be revisited; JT built against Jack 1.9.17 should be compatible with both old and new versions
- currently the resulting build does _not_ run on my machine when downloaded - it seems that it needs gcc libraries - not sure how this should be solved (but I think this PR is still valuable in the current form, and can be later updated for a functional build)
- I reverted the change in #230 since I couldn't get github actions …

Fix Windows builds in GHA

---

INSTALL.txt

I believe that we shouldn't suggest installing qjackctl with homebrew. AFAIU this will also pull jack1 from homebrew (which might cause trouble) and we already suggest installing current jack2 (which is good). Jack2 does provide qjackctl with the regular download.
IMO this should go to both `main` and `dev`, but definitely to `main` as this is the default branch - I'm not sure what's the best workflow procedure for this in the JT repo....?

INSTALL.txt: remove qjackctl reference

---

.github/workflows/jacktrip.yml
src/jacktrip.pro

I tried switching jack version on windows to 1.9.17 in GitHub Actions. This also required updating include and lib paths in the `jacktrip.pro` file.
Right now I'm checking for existence of both "new" and "old" Jack locations on windows and using the one that's found. If there is a better way to do this, I'd be happy to learn.
Previously we discussed pkg-config with Nils. I now think we shouldn't rely on it, at least for qmake build, as it's an additional dependency that needs to be installed on windows. Again, I wonder if there's a better way to search multiple library locations in plain qmake config. 
I've also tried [building](https://github.com/dyfer/jacktrip/runs/1989751578) with this change using the [old version](https://github.com/dyfer/jacktrip/runs/1989751578?check_suite_focus=tru …

Use Jack 1.9.17 in GHA, update qmake file for Jack 1.9.17 (Windows)

---

.github/workflows/jacktrip.yml
.github/workflows/meson.yml
meson.build
meson_options.txt
src/JackTrip.cpp
src/JackTrip.h
src/JackTripWorker.cpp
src/PacketHeader.cpp
src/ProcessPlugin.h
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/Settings.cpp
src/UdpDataProtocol.cpp
src/UdpHubListener.cpp
src/UdpHubListener.h
src/jacktrip_globals.cpp
src/jacktrip_main.cpp
subprojects/rtaudio.wrap
subprojects/wingetopt.wrap

- Meson gets RtAudio now if it's missing and builds it.
- RtAudio builds again (Jack disabled)
- CoreAudio for MacOS
- Alsa and Pulseaudio for Linux
- WASAPI for Windows
- Fixed MSVC build and Github Actions builds with MSVC
- uses meson wrap file for getopt (is POSIX API)
- Meson has options now: rtaudio, jack and wair
- Meson builds with C++17 as default
- There shouldn't be anything missing for meson in comparison to the jacktrip.pro file
- Skips duplicate Github Action builds
- Before: 12 builds ((3 old, 3 meson) *2)
- Now: 6 builds + 4 skip-duplicates (identifier jobs) + 2 skipped jobs

RtAudio Support, Meson Wraps, MSVC Support, Skip Duplicate Builds

---

.gitignore

This PR adds `.DS_Store` to the list of ignored files in the repository.
These files are created on macOS automatically. We should ignore them so that they don't show up in git as files changed in the repository.

Ignore macOS .DS_Store files

---

src/Compressor.h
src/Limiter.h
src/NetKS.h
src/ProcessPlugin.h
src/Reverb.h

Fixes #246 
It's hardcoding the names of ProcessPlugin's derived classes.

Hardcode Derived Class Names of ProcessPlugins

---

.github/workflows/jacktrip.yml

I've added static Qt builds to our GHA - qmake only for now.
Thanks @wholenotes for all the pointers. I've also found [this page](https://retifrav.github.io/blog/2018/02/17/build-qt-statically/) to be helpful, especially for the Windows build.
Here are some notes:
- Qt is built once and then cached
- initial build takes a long time (almost an hour), but subsequent builds for a given branch are fast, see [this job on my fork](https://github.com/dyfer/jacktrip/runs/2210027958?check_suite_focus=true)
- I used the latest Qt5 - 5.15.2; on Windows that probably doesn't matter (it supports Windows 7 and later). On macOS this probably means that we support only macOS 10.13 and later; I think previous JT releases used older Qt and thus might've supported older OSs (?). We could change the Qt …

Build static Qt in GHA on macOS and Windows

---

.github/workflows/jacktrip.yml
src/jacktrip.pro

I've added rtaudio static to our build system for macOS and Windows. RtAudio support is added to `qmake` with `-config rtaudio` flag.
Have not tested extensively - it just builds and runs for now. There seem to be no external dependencies (i.e. static library seems to be properly used).
I've removed some dead code in `jacktrip.pro` file from previously included rtaudio in the source. I'm using rt-audio from vcpkg and pkg-config to get the include paths and linker flags, so this means that windows builds with rtaudio will require installing pkg-config and rtaudio separately. I'd be happy to add that to the docs in another PR. (Building without rtaudio is still possible and doesn't require either library).
On Windows, I had a problem adding proper linker flags - it seems that we need to …

Build with rtaudio

---

.github/workflows/jacktrip.yml

Currently there is jack 1.9.17 available in homebrew. Linking against this version prevents from running with jackosx, due to difference in library name (no API conflicts), see https://github.com/jackaudio/jack2/issues/738
Linking against Jack 1.9.16 should make JackTrip compatible with both JackOSX and the newer Jack2.
EDIT: 1.3.0 release of JT is linked against Jack 1.9.16 since this was the version that was in homebrew at the time of releasing.

GitHub Actions: use jack 1.9.16 on macOS

---

meson.build

This should always compile rtaudio statically when it is a subproject.

Build rtaudio subproject statically (except for Windows)

---

src/AudioInterface.cpp
src/AudioInterface.h
src/JackAudioInterface.cpp
src/JackAudioInterface.h
src/JackTrip.cpp
src/JackTrip.h
src/JackTripWorker.cpp
src/JackTripWorker.h
src/PacketHeader.cpp
src/PacketHeader.h
src/RingBuffer.cpp
src/RingBuffer.h
src/Settings.cpp
src/Settings.h
src/UdpDataProtocol.cpp
src/UdpDataProtocol.h
src/UdpHubListener.cpp
src/jacktrip_main.cpp

The special case of 0 channels will not be part of this PR. It was already broken. We check now that number of channels won't be set to 0.
Resolves #78

Different number of input and output channels

---

jacktrip.pro

This should allow for linking to jack in various locations, particularly for building with pipewire.

Qmake: use pkg-config for Jack

---

src/AudioInterface.cpp
src/compressordsp.h
src/freeverbdsp.h
src/limiterdsp.h

Qt containers might lose their head if they are used in range based for loops. Consting the iterators with qAsConst helps.
Some range based for loops did some unnecessary copies.

Fix and optimize some for loops

---

.github/workflows/meson.yml
meson.build
subprojects/packagefiles/rtaudio/meson.build
subprojects/packagefiles/rtaudio/meson_options.txt
subprojects/rtaudio.wrap

This uses a RtAudio subproject build with meson instead of cmake. With this I get rid of a lot of linking errors on Windows. Qt is linked dynamically.

[Meson] Use rtaudio meson subproject instead of cmake

---

macos/assemble_app.sh
win/build_installer.bat

Checks to see if jacktrip has been built using static qt on windows and only sets path variables if they are not already set.
The script currently assumes the qt mingw tools are installed. If building with msvc, we'll need to copy different compiler dlls into the package, and possibly use dumpbin instead of objdump for the static qt test.

Check for static qt on windows

---

win/build_installer.bat

Just realised that qmake builds in builddir\release by default on windows. (Using cmake via kdevelop myself, so the binary is in builddir.) Have the script check which to use.

Check location of binary (windows install script)

---

src/Settings.cpp

Suggesting this new wording for --broadcast argument on help screen (changed in Settings.cpp): "Creates duplicate receive ports for each connected client that use the specified broadcast_queue length, to enable creating a broadcast output mix with added latency but less packet loss"

Change helpscreen wording for --broadcast argument

---

.github/workflows/jacktrip.yml
.gitignore
build
macos/package/JackTrip.pkgproj_template
win/files_static.wxs

I've updated the qmake build script and added creating macOS bundle to GitHub Actions (qmake build).
~~I've made following changes that I'd like to get feedback on (particularly @psiborg112 ):~~
- ~~In the bundle creation script, I changed `QJackTrip` to `JackTrip`. IIUC this is consistent with what we decided on the app name. Is that OK @psiborg112 ?~~
- ~~I've also renamed folder `os x` to `macos`; I'm happy to revert that change if you don't like it, please let me know.~~
The above changes were done outside of this PR.
I've also removed dynamic builds for macOS and Windows, and added a new Linux build with `nogui` option (also I plan to use that for running tests later). I think I'd also like to switch the main Linux build to static, just so it can be easily used for testing etc.
I've …

Update build script, create win/mac installers and mac application bundle

---

.github/workflows/mkdocs.yml

I think this should work :) - I don't think we want to make it run on forks (i.e. I don't have GH pages activated on my fork and I wouldn't want a copy of the main JT pages there anyway).
If we wanted, we could make it configurable per repository (fork) but I don't think that's needed - let me know if you think otherwise.

gha mkdocs: run only on the main repo

---

CMakeLists.txt
jacktrip.pro
meson.build
src/main.cpp

If no x or wayland display is set, show the user a more informative error message than the qt plugin one that otherwise appears.
Also, replace \_\_NO_GUI\_\_ with NO_GUI (addresses part of #276)

Replace cryptic error message on linux if no X or Wayland display

---

.github/workflows/jacktrip.yml

In preparation for the release:
- added automatic uploads of artifacts to the GH release page
- I'm not uploading Linux binaries due to issues with the static Linux build
- tagged builds have tag included in the filename
- single files have to be double-zipped when downloaded straight from actions (so that they show up as a regular zip on the release page)
- changed GHA to run on main + dev, PR and on schedule to refresh cache (on schedule will become active once merged into main)
- removed skip duplicates
_After this PR GHA won't run on all pushes, just PRs, after merges to dev/main and eventually "on demand"_ (after merging this to main, i.e. after the 1.4.0 release)
You can see artifacts in actions from a tagged commit form this branch here: …

Automatic upload of release artifacts

---

.github/workflows/jacktrip.yml

Not sure when we'll be able to use it, but we should definitely be able to use ASIO on Windows eventually, which requires this change.

gha qmake: use rtaudio with asio

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/main.cpp

Alert the user that command line options are currently ignored in GUI mode. And if they manage to stumble upon --test-gui, let them know they need to remove it for jacktrip to run normally.

Add warning for command line arguments in GUI mode

---

.github/workflows/meson.yml
.gitmodules
jacktrip.pro
meson.build
meson_options.txt

This moves weakjack from the subprojects directory into JackTrip's own src directory because weakjack is not a subproject. The subprojects directory is a special meson directory that is protected to only contain subprojects. Weakjack is supposed to be part of your projects source code (copied or as a git submodule).
Additionally this PR adds a weakjack option for meson. Tested on Linux. This seems to be broken with QMake because of the dl dependency.
PS: QMake is slow… and links jacknet because of some reason.

Weakjack part2

---

mkdocs.yml

Sets edit_uri to dev branch. If you click on the edit symbol in a docs page you should be directed to the correct edit page on github.
Please rebase merge as it is only one commit!

[Docs] Make edit symbol work

---

.clang-tidy
src/AudioInterface.cpp
src/AudioTester.cpp
src/Effects.h
src/JMess.cpp
src/JMess.h
src/JackTrip.cpp
src/Limiter.h
src/Settings.cpp
src/compressordsp.h
src/freeverbdsp.h
src/freeverbmonodsp.h
src/limiterdsp.h
src/main.cpp
src/zitarevdsp.h
src/zitarevmonodsp.h

Let's start using clang-tidy with only two enabled checks. It's easier to review.

Add Clang-Tidy: Modernize deprecated headers, use range-based for loops

---

.github/workflows/jacktrip.yml

This should fix the Linux static build... tested on Ubuntu only.
~~It turned out, that in order to build static Qt that runs in X11, one needs to bundle the qt `xcb` platform plugin. This has been [disabled in Qt 5.15](https://doc.qt.io/qt-5/linux-requirements.html), but is still [possible in Qt 5.12](https://doc.qt.io/qt-5.12/linux-requirements.html).~~
It turned out that bundling xcb platform plugin was not necessary. Qt 5.15 seems to be incompatible with the distribution I was testing with (Ubuntu 20.04, running X11). 
Compatibility with Wayland is still TBD.
In this PR
- I made the qt version configurable in the build matrix
- I set Linux and macOS to use Qt 5.12
- ~~on Linux, I've used build flags specifically for 5.12, namely `-qt-xcb`, which bundles the xcb plugin with the library; …

Fix static Linux build in GitHub Actions

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.ui

Add buffer size setting to RtAudio settings in the GUI. Fixes #331.
I've edited `qjacktrip.ui` by hand - feel free to correct as needed.

UI: add buffer size setting for RtAudio

---

win/build_installer.bat

Wix only supports version numbers of the form x.x.x. Strip the rc part of our version to build the installer.

Strip rc part of version for windows installer script

---

linux/org.jacktrip.JackTrip.metainfo.xml.in

The Flatpak GHA uses the appstream file on dev. So any update to the PR's appstream doesn't change the behavior of the flatpak GHA. So this should fix the GHA after it's merged.

[Appstream] Update appstream and fix flatpak GHA

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/qjacktrip.ui

If built with weakjack, check if jack is available. If not and the rtaudio backend has been built in, fallback on this and show a warning dialog which the user can choose to hide in the future. If no other backend is available, show a warning that cannot be suppressed.
Also, remove redundant code to change UI based on audio backend choice in the loadSettings function. (This is taken care of when the backendComboBox value is set via the connected signal and slot.)

Check if jack is available

---

.github/workflows/flatpak-release.yml
src/jacktrip_globals.h

- ~~fix XML file, as suggested by @ntonnaett~~
- update version to 1.4.0-rc.2
- flatpak stable deployment only runs on the main branch (as requested by @ntonnaett)
~~EDIT: I removed changes to the flatpak XML file from this PR as they did not work. I don't know what's wrong there - [here's what I've tried](https://github.com/dyfer/jacktrip/blob/xml-change-copy/linux/org.jacktrip.JackTrip.metainfo.xml.in).~~
~~Flatpak GitHub Action failure should not interfere with the release candidate, so IMO we can go ahead with rc.2. I think @ntonnaett is on board with that :) ~~ Flatpak issue is now resolved

Prepare 1.4.0 rc.2

---

src/AudioInterface.cpp

This fixes:
```
==16328== Invalid read of size 8
==16328==    at 0x46DC40: AudioInterface::~AudioInterface() (AudioInterface.cpp:115)
==16328==    by 0x4768B5: JackAudioInterface::~JackAudioInterface() (JackAudioInterface.cpp:92)
==16328==    by 0x4768D1: JackAudioInterface::~JackAudioInterface() (JackAudioInterface.cpp:92)
==16328==    by 0x418CF9: JackTrip::closeAudio() (JackTrip.cpp:283)
==16328==    by 0x41C45A: JackTrip::stop(QString) (JackTrip.cpp:953)
==16328==    by 0x414D59: JackTrip::slotStopProcessesDueToError(QString const&) (JackTrip.h:526)
==16328==    by 0x41FC0E: QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<QString const&>, void, void (JackTrip::*)(QString const&)>::call(void (JackTrip::*)(QString const&), JackTrip*, void**) (qobjectdefs_impl.h:152) …
```

Fix process plugin delete

---

src/JackAudioInterface.cpp

This fixes a crash when jacktrip uses more channels than physical ports are available.

Fix connecting default ports with high numbers of jacktrip channels

---

src/JackAudioInterface.cpp

This prevents indirect memory leaks (at least in pipewire). Jack's
simple_client looks like this shouldn't happen and is probably a
bug in pipewire. But unregistering ports doesn't hurt.

Unregister jack ports before closing client to prevent indirect memory leaks (with pipewire)

---

meson.build
src/AudioInterface.cpp
src/CompressorPresets.h
src/JackTrip.cpp
src/RtAudioInterface.cpp
src/jacktrip_globals.h

This prevents warnings from tools like clazy that we can't fix. It's a really big cleanup. So I fixed already two for loops that I missed the last time.

Include Qt5 with -isystem in Meson and fix some clazy warnings

---

src/JackTrip.cpp

Allow users to use "JackTrip" as a custom client name. (Fixes regression in #359.)

Fix client name edge case

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/qjacktrip.ui

Move the audio backend settings into their own tab. This will declutter the basic options tab and give us space to implement additional backend settings moving forward.

Backend tab

---

meson.build

This is based on discussions in #361 
- Add a workaround for missing coreaudio linking flags in RtAudio's pkgconfig file
- ~~Add an option to set if RtAudio should be linked statically (even with package manager's rtaudio or default_library=shared)~~

Meson ci fixes

---

docs/Build/Meson_build.md

I think we should be careful about suggesting installation of jack with homebrew. Arguably most users would install Jack with the graphical installer. Homebrew might clash with that installation.

macOS meson instructions update

---

build
docs/Build/Linux.md
docs/Build/Mac.md
docs/Build/Windows.md
jacktrip.pro

This PR aims to add Linux desktop resource installation for feature parity with the `meson` build. Changes include:
- creation of `.desktop` and `.metainfo` files
- copying and renaming icons
- adding `install` option to the `build` script
- updating Linux build instructions
- ~~**possibly unrelated change**: on my Ubuntu 20.04 system jack was not found with pkg-config. I tried to fix it, but did not manage to do it (I've reinstalled `libjack-jackd2-dev` and `pkg-config` but that did not fix it); I've then added a flag in our `jacktrip.pro` to check if `jack` flags are available from `pkg-config`, and if not, use the previously hardcoded flags (`-ljack`), which works on my system. Let me know in case this change should be removed or put in a separate PR.~~ I reverted this change - it's …

QMake: Linux installation improvements

---

meson.build
meson_options.txt

The formatting is missing but the output looks something like this:
```
Audio Backends
JACK: YES
Weak JACK Linking: NO
RtAudio: YES
Configuration
Application ID: org.jacktrip.JackTrip
GUI: YES
WAIR: NO
Manpage: YES
```

[Meson] Add Summary

---

linux/org.jacktrip.JackTrip.metainfo.xml.in

As discussed in #387, `<releases>` tag is not strictly required and it's additional burden to keep that file updated in addition to the changelog. 
@ntonnaett, would you be okay with removing that section for now? We might come up with an automated way to populate that in the future, if desired.
This potentially fixes #387

AppStream - remove releases info

---

linux/org.jacktrip.JackTrip.metainfo.xml.in

Removes the German translation that doesn't work as expected and Remove some capitalization (https://blogs.gnome.org/tbernard/2021/09/07/ready-for-software-41/).

Metainfo summary fix

---

.github/workflows/flatpak-devel.yml
.github/workflows/jacktrip.yml

This changes artifact names to use short SHA (first 7 digits)
I've also attempted to change the name for Flatpak dev build. @ntonnaett is the capitalization OK? I wanted to make it consistent with other artifacts.

GitHub Actions: use short SHA in artifact names

---

CMakeLists.txt
macos/assemble_app.sh
src/JackTrip.cpp
src/JackTrip.h
src/Settings.cpp
src/Settings.h
src/main.cpp
win/jacktrip.wxs

Add an option to specify the binary location in the MacOS packaging script to allow easier signing of downloaded github artifacts.
Allow upgrades with Windows installer.
Use a smart pointer for the AudioTester so that we don't need to keep the Settings object around.

Update installer scripts

---

src/gui/qjacktrip.cpp

Prevents connection errors if someone has copied and pasted a server address into the GUI with leading or trailing whitespace.

Trim whitespace from server address

---

src/JackTrip.cpp

#419 might not have been enough to fix the possible buffer size mismatch with RtAudio (and ASIO) because the jacktrip class has its own buffersize variable. This should fix it.

[RtAudio] Set mAudioBufferSize in jacktrip after RtAudio setup

---

src/gui/qjacktrip.ui

Moving username/password fields for authentication to advanced tab, since most users will likely assume this is asking for the Virtual Studio credentials.

Moving authentication options to advanced tab

---

src/jacktrip_globals.h
subprojects/rtaudio.wrap

This fixes the failing CI meson builds. Sets the RtAudio version of meson's rtaudio subproject to 5.2.0.
Edit: I added rtaudio to Meson's wrapdb and updated our wrap file accordingly. So if the version in wrapdb gets updated it's only `meson wrap update rtaudio`.

[Meson] Set RtAudio subproject to version 5.2.0

---

CMakeLists.txt
jacktrip.pro
meson.build
src/JackTrip.cpp
src/JackTrip.h
src/JackTripWorker.h
src/Settings.cpp
src/Settings.h
src/UdpHubListener.h
src/gui/messageDialog.cpp
src/gui/messageDialog.h
src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/qjacktrip.ui
src/gui/qjacktrip_novs.ui
src/gui/textbuf.cpp
src/gui/textbuf.h
src/main.cpp

Enable the verbose flag to be set from the command line while using the GUI. (jacktrip --gui -V)
Also detect whether the program has been run from the command line on windows so that we don't detach ourselves from the console. (Otherwise we won't get any output on the terminal.)

Verbose mode in GUI

---

.github/workflows/jacktrip.yml

I just recognized that we have gha builds every minute right now. So I thought there might be someone who's tampering with our stuff. But our cron job entry is just wrong. Right now every minute on sundays a jacktrip build is started. I think one time a week instead of 1440 times is sufficient.
https://crontab.guru/#0_0_*_*_0

[GHA] Fix weekly cron job entry

---

docs/changelog.yml
src/Patcher.cpp
src/Patcher.h
src/Settings.cpp
src/Settings.h
src/UdpHubListener.h
src/gui/qjacktrip.cpp
src/gui/qjacktrip.ui
src/gui/qjacktrip_novs.ui
src/jacktrip_globals.h

Add an option in the GUI and command line (-u, --upmix) to allow for mono clients to be upmixed to stereo in the built in hub server patch modes. (Potential solution for #449)

Add an option to upmix mono clients when patching

---

.clang-tidy
src/JMess.cpp
src/JMess.h

'using namespace' is a time bomb. Let's remove it. Edit: And forbid it with clang-tidy.
There's also `const int Indent = 2;` nearby. What's the intent? Didn't find a use.

Remove 'using namespace std' from JMess header

---

docs/changelog.yml
meson.build
src/jacktrip_globals.h

Just saw that in meson the weakjack include directory is unnecessarily added when it's actually disabled.
Bumps version to 1.5.1. But we might want to wait for more changes.

Clean up weakjack include

---

src/JackTrip.h
src/Patcher.cpp
src/Patcher.h
src/Settings.cpp
src/Settings.h
src/UdpHubListener.cpp
src/UdpHubListener.h
src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/qjacktrip.ui
src/gui/qjacktrip_novs.ui

Add an option to include the server in the patching for client fan out/in and full mix modes. This allows an ensemble member to more easily run a server and their own audio on the same machine.
I've technically implemented these as patch modes 6 and 7, but am using a checkbox in the GUI as a modifier to the existing patch modes. Haven't implemented it on the command line yet and am open to suggestions on whether to add them to the -p list or to use a solution similar to the one in the GUI (ie, an additional switch).

Options to include server in patching

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/main.cpp

The dialog that warns that most command line options are ignored with the --gui switch was not being shown in some cases when verbose mode was already set in the GUI. Also, remove manual formatting of dialog box contents.

Fix GUI command line warning

---

src/UdpDataProtocol.cpp

Remove leading underscores from preprocessor definitions that aren't reserved compiler definitions.

Rename __MANUAL_POLL__ to MANUAL_POLL

---

src/UdpDataProtocol.cpp

One of the quirks of the pre-IPv6 networking code was that we called connect on our UDP socket. The benefit was that we could just call send rather than sendto and it would only accept packets arriving from the specified destination.
I abandoned it for IPv6 because adapters commonly have multiple addresses and there was no guarantee that packets would be arriving back from the same address. I kept it for IPv4 because if it ain't broke... But it is broken. It seems to cause issues with both epoll and kqueue causing them to report that the socket is ready for reading when there's no data on it. Fixes #474.
(Also, clean out some of the very old and very broken 'two sockets on a single port' code.)

Don't connect our UDP socket

---

.github/workflows/jacktrip.yml

This is mostly a housekeeping PR aiming to optimize our GHA builds.
The main change I'm suggesting is to use bundled rtaudio in static Windows release builds (currently we use the build from vcpkg, which does get built every time anyway). I'll test this build before marking the PR ready for review to make sure there are no regressions.
Reasoning: 
Using bundled rtaudio is much easier on Windows than installing the library using vcpkg (at least until a better solution is implemented, like moving to MSYS2). Thus I'd like to **use bundled rtaudio as the default approach for building the release artifacts** on Windows. Using rtaudio from vcpkg is still supported and tested for (in the shared library Windows build). 
This PR also removes one build from our already considerable build matrix, …

Use bundled rtaudio for Windows release builds

---

build

I've tried to build JackTrip on macOS 11.6 under Xcode 13.2 on m1 hardware (arm64)
TL;DR:
JackTrip builds and runs fine on arm64 mac (aka Apple Silicon / M1).
The good:
- with this change JackTrip builds
- works fine with Jack and RtAudio
~~The bad~~
- ~~doesn't work with RtAudio~~
**There is no issue with RtAudio**, something was wrong with my system. RtAudio backend works fine after restarting.
~~I'm not sure if we want to merge this PR in the current form. While it provides the minimum to detect the architecture and build in qmake, we might also consider being able to set architecture (e.g. to cross-compile or compile universal binary)~~ EDIT: I think it's fine as it is. I think cross-compiling is a topic to be considered at a later stage.
Also: 
- meson build worked fine on arm64 with …

macOS arm64

---

docs/Install.md

the apt install and other package managers installation steps install older version. Making this clear to users.

Update install page to call out old versions on Debian and others

---

build

QMake build script would not exit if the build command failed and thus the CI would not report failure. This PR fixes that behavior, making the build script exit with the appropriate code if one of the build command fails.
Fixes #494

QMake build script: exit when build fails

---

src/JackTrip.cpp

The current JACK universal build (1.9.20) doesn't cleanly close the client on arm64 and triggers the jack_on_shutdown callback when it forcibly removes it. This workaround prevents the GUI from incorrectly reporting that the JACK server has shutdown.

Fix false error message (M1 builds)

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.ui
src/gui/qjacktrip_novs.ui

Remove the RtAudio warning for official builds and tweak it for NO_JTVS builds (the binaries maintained by @psiborg112).
Additionally, save if RtAudio has been used as a fallback option rather than selected as a deliberate choice by the user. That way, if JACK is installed later, it can be reinstated as the default backend. (NO_JTVS builds)

RtAudio warning changes

---

.github/workflows/jacktrip.yml
jacktrip.pro

This also changes the nogui build to use static qt (I don't think we need both shared and static nogui build right?)
Fixes #509
(I haven't tested the actual release, but the build itself should be available in the artifacts of this PR once it's built)
EDIT: just to be clear, I don't expect there will be any issues with the release - the release artifact name is specified. I just haven't tested this so let's look out for this at the next release after this is merged.

GHA: include Linux nogui static build in the release

---

.github/workflows/jacktrip.yml

I think that it is confusing to users to have to choose between application bundle, single binary, and an installer for macOS.
I propose that for the release (and generally build artifacts) we do not upload a single binary for macOS - we offer the application bundle already and the binary can be accessed inside it if needed.
See discussion in #512

macOS: disable upload of the jacktrip binary

---

src/UdpDataProtocol.cpp

When trying to build jacktrip on Alpine Linux for my Docker container I've got some warnings. One commit fixes the include path for fcntl.h.
The second commit doesn't fix the warning about non initialized struct members but changes the setRealtimeProcessPriority() function to be C on POSIX systems. Designated initializers are part of C since C99 but were introduced in C++ only with C++20. As this change doesn't fix anything I'm open to remove this. Happy to hear your opinion.

Fix include path to fcntl.h

---

.clang-format-ignore
faust-src/faust2header.cpp

Let's ignore faust's formatting.

Clang format ignore dsp

---

src/JackTrip.cpp
src/Regulator.cpp
src/Regulator.h

for eventual 1.5.4 release
server and client can have different FPP (tested from FPP 16 to 1024)
stress tested by repeatedly starting & stopping across full range of FPP's
server and client can have different in / out channel count
auto mode -- use -q auto
or for manual setting of initial mMsecTolerance -- use -q auto<msec>
gathers data for 6 sec and then goes full auto

Plc asym auto fix

---

.github/workflows/jacktrip.yml

Pulling from vcpkg instead of chocolatey gives us access to the static openssl libraries

Fix OpenSSL in build script (fixes #515)

---

.github/workflows/jacktrip.yml
src/gui/Browse.qml

This seems to be the one issue in the code that is keeping things from running on 5.12. I have tried to move our builds to 5.15 unsuccessfully and am going to wait until we move to qt6 to continue down that path. 
For now, here is a fix. 
Going to test this before upgrade to a full PR.

Adapt QML for 5.12 on Linux

---

.github/workflows/jacktrip.yml
src/gui/virtualstudio.cpp

Swapping the callback port from 42424 to 52424 to avoid a collision experienced in testing. This is in a range that is less likely to have collisions overall.

Port change to avoid collisions

---

src/gui/virtualstudio.cpp

After logging into Virtual Studio, the default message displayed in your browser window is cryptic and looks bad. It's just raw text:
`Callback received. Feel free to close this page.`
This overrides the default with a more user friendly confirmation.

More user friendly confirmation of Virtual Studio login success

---

src/gui/Setup.qml
src/gui/qjacktrip.qrc
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml

This comes up after login. That means it loads every launch if you're using Virtual Studio mode. It's basically the top portion of the settings menu. 
I wanted to do device selection in the Connected screen but found managing the necessary disconnect/reconnect work to be too cumbersome for the time I have at the moment.

VS: Add device setup screen after login

---

macos/JackTrip.app_template/Contents/Info.plist

Per https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion - this also might be needed for various update-checking tools but that's not fully clear to me yet. 
I looked through a bunch of apps I have installed in `/Applications` and they all seem to use semantic versions for this key.

Update CFBundleVersion with semantic version

---

.github/workflows/jacktrip.yml
.github/workflows/jacktriplabs.yml
docs/Build/Meson_build.md

In homebrew apparently package name is `rtaudio` now, and not `rt-audio`, per [documentation](https://formulae.brew.sh/formula/rtaudio).
See https://github.com/jacktrip/jacktrip/runs/6540304068?check_suite_focus=true#step:6:47 for a warning in the CI.
This PR changes occurences of the old name project-wide.

update homebrew rtaudio name

---

docs/changelog.yml

Here's an update to the changelog for 1.6.0. These changes are automatically propagated in the docs and also used in the Flatpak release I believe.
I've used an arbitrary future date, we might want to adjust this for the final 1.6.0 release.
I tried to synthesize the most important updates from the ones that are autogenerated in our [RCs](https://github.com/jacktrip/jacktrip/releases). Please let me know if anything is missing or should be phrased differently!
This fixes #587

Update changelog.yml for 1.6.0

---

releases/edge/mac-manifests.json
releases/edge/win-manifests.json
src/dblsqd/feed.cpp
src/jacktrip_globals.h

This fixes a bug I encountered when trying to use the Github release download URL (ex: https://github.com/jacktrip/jacktrip/releases/download/v1.6.0-rc.2/JackTrip-v1.6.0-rc.2-macOS-x64-signed-installer.pkg) as the source of the package.
dblsqd expects the installer package filename to be the last segment of the URL. That works for the `https://files.jacktrip.org/app-builds/...` links because they point directly at builds, but the `https://github.com/jacktrip/jacktrip/releases/download/...` URLs are actually redirects to `https://objects.githubusercontent.com/...`. The redirect location doesn't include the filename in the URL anymore, but instead in the query parameters.
Also, bumping to rc3

Apply workaround to enable dblsql to update from github releases

---

.github/workflows/jacktriplabs.yml

I proposed that we update the name of the JackTrip Labs workflow, so that it's easier to identify it (and identify regular builds) in the list of actions in PRs etc. 
I'm open to other names etc, I just would like it to be different from the regular `build`.

GHA: update name of the jacktrip labs workflow

---

src/dblsqd/feed.cpp

Minor enhancement, but this should harden the regex a little bit in case the order in which the query parameters appear changes in the future

Updating filename extraction regex to be position-independent

---

releases/edge/mac-manifests.json
releases/edge/win-manifests.json

Currently rc.2 continues to auto-prompt because the application version is still marked as rc.1

Updating release manifests for rc.3

---

src/gui/virtualstudio.cpp

It would only previously work if the input device name == output device name, due to a typo in the code.

Bug fix for erroroneous "device not found" when using virtual studio mode

---

src/UdpDataProtocol.cpp

I believe this is the latest standard for quality of service in routers. Expedited Forwarding (EF) is recommended for real time audio streams.

Set ToS IP header to use DSCP Expedited Forwarding for audio packets

---

.github/workflows/jacktrip.yml
src/gui/Login.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml

Deep Google searches led me to these two issues which seem to fix the auth flow behavior on Ubuntu 20.04:
* https://bugreports.qt.io/browse/QTBUG-84866
* https://stackoverflow.com/questions/69585272/c-signal-is-not-received-in-qml-slot
I've also enabled the "Back" button on the "Logging in" screen so you can return to the original start state if it ever does hang again.
The more appropriate fix would be to use QT 5.15.x for Linux (which we're already using for Mac + Windows) but that's currently not an option for reasons beyond my knowledge.

Fix perpetual "Logging In" screen

---

.github/workflows/jacktrip.yml

It seems that there is a a newer version of 5.12 available, let's use that on Linux.
~~This _might_ help with #615, but it's not only a guess.~~ EDIT: it does not fix that issue.
EDIT 1: Windows and Flatpak build failures are unrelated to this change
EDIT 2: Before merging, please download and run the Linux build. ~~For the record, please check if it by any chance changes the behavior observed in #615~~

GHA: update static Qt version on Linux

---

src/gui/virtualstudio.cpp
src/gui/vsWebSocket.cpp
src/gui/vsWebSocket.h

I found that we don't need to recreate `VsWebSocket` since that class itself is just a wrapper around the actual QWebSocket pointer.
This should also closely mirror how the bridge devices execute heartbeats, which is:
* When not connected to a studio, use the POST API
* When connected to a studio, use the websocket
In practice, I'm seeing there is a small gap in behavior because of the non-blocking nature of these QT libraries. For example, I added this line:
```cpp
qDebug() << now << "Websocket valid" << m_heartbeatWebSocket->isValid();
```
to confirm the behavior above, and what I saw was:
```
<after opening the app>
"2022-06-24T16:26:03Z" Websocket valid false
<after joining studio>
...
step 7
UdpDataProtocol:run1 before mJackTrip->parseAudioPacket()
Received Connection from Peer!
step …
```

Adding closeSocket method for finer control of socket handling

---

CMakeLists.txt

There were several occasions that people tried to build jacktrip with cmake and complained about missing features (e.g. #637). This change adds a warning to the cmake build that the cmake build is not supported and that Meson and QMake are recommended.

Add warning that cmake build is not officially supported

---

jacktrip.pro
meson.build

We said we weren't going to include the dblsqd updater on Linux as the various package manager manage updates.

No dblsqd on Linux

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml
src/gui/vsUrlHandler.cpp
src/gui/vsUrlHandler.h
src/main.cpp

When clicking that semi-hidden testUrlScheme button, this joins the SF public studio and changes the view.
TODO: Error states (studio not found, bad path params and identifiers, etc.)

Enabling join + connected view experience

---

.github/workflows/jacktrip.yml
.github/workflows/jacktriplabs.yml
src/vsPinger.cpp

Fixes an edge case bug when computing statistics for a size 0 vector. This PR resolves the bug by setting the min, max, average, and standard deviation to be 0 if the vector is size 0.

fixes bug in computing stats on size 0 vector

---

.clang-tidy-ignore

Adds .clang-tidy-ignore file. This should silence clang-tidy GHA for all dsp headers.

Add .clang-tidy-ignore file

---

.github/workflows/jacktrip.yml
.github/workflows/jacktriplabs.yml
rtaudio.pro

Fixes #671.
This ~~is an attempt to~~ fixes compatibility with macOS 10.13. RtAudio from homebrew is built for macOS 10.14 and later AFAIU so building RtAudio ourselves ~~might fix this~~ is necessary to support an earlier OS.
Changes in this PR:
- JT GHA: main macOS build uses bundled RtAudio
- JTLabs GHA: macOS build uses bundled RtAudio
- qmake file for RtAudio now specifies the same deployment target as JackTrip's qmake file
- deployment target is set very low - 10.9 - but the current build practically supports only 10.13 and up. This is due to Qt's compatibility - Qt 5.15, which we use on macOS for the release builds, supports 10.13 at the earliest.
- JT GHA: shared macOS build (non-release) uses system RtAudio (for testing build configuration)
- affected actions are renamed to …

Use bundled RtAudio on macOS - fix compatibility with macOS 10.13

---

src/jacktrip_globals.h

Bumps global `gVersion` value to `1.6.2-rc.3`

Update jacktrip_globals.h for 1.6.2-rc3

---

src/gui/Browse.qml
src/gui/Studio.qml
src/gui/manage.svg
src/gui/qjacktrip.qrc

People have been confused thinking the "Manage" gear in an inactive Studio will take them to audio settings. So this replaces it with an "Open in new window" icon and adds a settings gear to the actual settings button in the bottom right.

VS: Replace "Manage" icon

---

src/gui/virtualstudio.cpp

In VS mode it will now say "The Studio has been stopped" the message box instead of "Peer Stopped".

VS: Change peer stopped message

---

src/JackTrip.cpp
src/RtAudioInterface.cpp
src/gui/virtualstudio.cpp

What this change _actually_ does is pass RtAudio errors up to Qt for JackTrip to handle. If a GUI is present, the GUI handles it gracefully. 
In classic mode, it just pops up a message box and refuses to connect.
In Virtual Studio mode, it pops up a message box and goes back to the browse screen.

Don't crash on unsupported RtAudio sample rate

---

src/main.cpp

Fixes #688
This applies primarily to Windows, when the display scaling is set to 150%, 125%, 175% etc. Previously, the interface was rendered at 100% or 200% (most noticeable for 150%, which was rendered at 200%). With this change, the interface is scaled accordingly to to the fractional scaling.
This might also apply to Linux, although not for our static build, which uses Qt 5.12 (the fix is only valid for Qt 5.14+).
macOS was already behaving correctly.
Reference: https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt

UI: fix fractional UI scaling on Windows

---

.github/workflows/jacktrip.yml
.github/workflows/jacktriplabs.yml

I was puzzled to see that our scheduled builds [did not use](https://github.com/jacktrip/jacktrip/runs/7822792936?check_suite_focus=true#step:11:17), nor update, static Qt cache.
It seems that access to events that are triggered on schedule was [added to the newer version of the cache action](https://github.com/actions/cache/issues/63#issuecomment-629422053). I've updated our cache actions accordingly.
I've made the changes to both jacktrip and jacktrip labs workflows.
IMO this should make its way into `main` as soon as possible, as scheduled actions are based on the default branch. Thus, I'd like this to go in before releasing 1.6.2.

GHA: update cache actions

---

releases/edge/mac-manifests.json
releases/edge/win-manifests.json

Forgot to include this in the last PR

Update edge manifests with 1.6.2 release

---

.github/workflows/jacktrip.yml
.github/workflows/jacktriplabs.yml

Okay, this time for real... (?) 
It turns out, that my last fix for cache [did not fully work](https://github.com/jacktrip/jacktrip/runs/7887245774?check_suite_focus=true#step:50:2).
cache action@v1 [supports](https://github.com/jacktrip/jacktrip/runs/7866917357?check_suite_focus=true#step:50:3) relative paths (which we used for the static qt build), but does not work on scheduled jobs (that's why I updated it for 1.6.2).
cache action@v2/v3 works on scheduled jobs, but does not support relative paths... which this PR fixes.
This PR changes the location of the static qt build, which fixes caching with the new version of the action. IUUC, cache should also now work for the scheduled jobs (but we'll get the confirmation once the scheduled job gets triggered...)
The caching of the static …

Fix cache for real

---

CMakeLists.txt
src/main.cpp

Don't install the custom message handler when we haven't initialised the text stream.

Fix qDebug segfault

---

docs/changelog.yml
src/jacktrip_globals.h

Given the work by @psiborg112 in #704 to solve the segfault when creating servers and myself #706 to make sure the linux desktop file validates correctly, we should release 1.6.3. This is prep for that PR.

Bump global to 1.6.3 for release

---

src/gui/vsDevice.cpp

Fixes a bug where network stats do not display on first run or after an upgrade. The issue is that the device emulator tries to initialize a websocket with empty credentials `m_apiPrefix` and `m_apiSecret`. This resolves the issue by delaying the call to `sendHeartbeat()` until after the credentials are generated.

delay heartbeat until after device is registered

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

This should fix the bug causing Virtual Studio to immediately go to the Connected screen upon clicking a Join link from Virtual Studio web app.
The cause is that `joinStudio()` was being called too early, immediately after the call to `setStudioToJoin()`. This PR resolves the bug by removing the signal. 
Simulating a deep link from the command line (additionally also works for first time users with sign in):
https://user-images.githubusercontent.com/26987971/186782714-cfe78cc4-1bf4-4e2a-9d1f-ef47efb68c96.mov

Bugfix: Join Button from VS-Web Skips Setup

---

src/Regulator.cpp

if a client stalls out, a worker using PLC was uselessly processing the last good packet and driving up load

PLC avoid processing same packet -- zero instead when extreme underrun 

---

src/jacktrip_globals.h

There's a lot to test with volume meters in VS mode, so can we go ahead and cut a release candidate for 1.6.4?

Let's cut RC1 of 1.6.4

---

src/gui/Browse.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

#712 made it so refresh button never emitted `refreshFinished`, and this fixes that while keeping the benefits of #712

Re-enable refresh button

---

.github/workflows/jacktriplabs.yml

We didn't fully update `jacktriplabs.yml` when we bundled rtaudio with the macOS release to fix High Sierra.

Sign bundled_rtaudio build

---

src/Regulator.cpp

'good underruns' = those under a 30ms threshold (same as used for the UPD waiting too long msg)
'bad underruns' = stuck clients beyond that threshold
the former are likely jitter and should get processed, 
the latter should'nt due to the high DSP load incurred (output zeroes instead)

PLC distinguish stuck clients

---

docs/changelog.yml
src/jacktrip_globals.h

There's a **_LOT_** that's ready to go, so let's get 1.6.4 out the door.

Update version and changelog for 1.6.4 release

---

releases/stable/linux-manifests.json

Only adding this to stable, since there currently is no Linux installer or auto-update functionality. This is only going to be used to automatically redirect download links to the latest version via https://jktp.net/download/linux

Adding linux manifests

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

Makes inactive studios visible by default and deletes filter and warning preferences on logout.

VS: Adjust default behavior on login

---

src/gui/virtualstudio.cpp

Before this fix, if you attempt to logout during the same app session that you logged in, the app will hang on "Logging in..." instead of showing you the "Sign In" and "Back" buttons.
This is because `getUserMetadata()` was failing due to `m_userID` being empty when it was run. This meant that technically, auth failed despite us getting a refresh token, etc. So the app was still waiting for a login. 
I just adjusted it to
1. Only `getUserMetadata` if `m_userID` existed
2. Attempt to `getUserMetadata` if it was empty after every `getUserID`
No more `authFailed`.

VS: Fix logout freeze

---

src/gui/vsDevice.cpp

"-q auto" normally sets buffer length to -500, but this isn't a sane value when using loss concealment. "-q auto3" is the recommend value, which is equivalent to -3 or 3ms of headroom.

Use sane buffer length for loss concealment in virtual studio mode

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/main.cpp

Allows the app to quit as expected when closing the window or hitting the exit button. With this change, the NO_VS build seems to work fine when built with Qt6.

Fix exit button in qt6

---

.github/workflows/jacktrip.yml

The address to qt sources has changed. We haven't noticed it on our builds since we've been using cached Qt. But it would become an issue once we need to rebuild Qt, probably at the release.
~~Moreover, I realized that a newer version of Qt 5 is available (5.15.6) so I updated our builds to use that.~~
EDIT: It turns out that Qt sources 5.15.3 - 5.15.6 have a different filename (`qt-everywhere-opensource-src-5.15.N.tar.xz` instead of `qt-everywhere-src-5.15.N.tar.xz`) so I reverted the update to the Qt version, since that would need some extra work in the workflow file. We can still do it if we have a real need to use 5.15.6, but I don't think that's the case right now, so I'm leaving it as is.
Example of the new link:
`https://download.qt.io/archive/qt/$QT_MAJOR_MINOR_VERSION/$QT_FULL_VER …

Update static Qt

---

src/dblsqd/feed.cpp
src/dblsqd/semver.cpp
src/dblsqd/semver.h

Change from the deprecated QRexExp class to the QRegularExpression class to allow dblsqd to compile under Qt6.

Allow updater to build with Qt6

---

src/Meter.cpp
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

This just creates a detached copy of the vector before emitting it
Added a check to ensure updateNumChannels can only be called before init; otherwise, resetting the mValues vector could cause corruption
Update virtual studio slots for vumeters to use const references, since it should not be necessary to create unique copies on every trigger of the signals

Potential fix for crash involving vumeters

---

build
jacktrip.pro
rtaudio.pro

I wanted to test building with Qt6 and in the process made changes that make the build script more flexible.
The script now extracts the qmake spec from `qmake -query` command, instead of hardcoding it for each platform. I'm not sure that's even needed (it returns the default spec), but I'm leaving it in for now.
I removed macos deployment target setting, since I realized that the [qt documentation](https://doc.qt.io/qt-6.2/macos.html) says:
> Note: You should not lower the deployment target beyond the default value set by Qt. Doing so will likely lead to crashes at runtime if the binary is then deployed to a macOS version lower than what Qt expected to run on.
So, IIUC, deployment target setting should only be used to set a deployment target _higher_ than the one set by Qt.
I believe …

QMake updates

---

src/gui/about.cpp
src/gui/about.ui

Now that people are starting to build with different versions of Qt, show which version the app has been built with in the about dialog box.

Show Qt Version in about dialog

---

macos/assemble_app.sh
macos/sign-stuff.sh

Apple has deprecated altool and will stop supporting it from next year. Switch to using the new notarytool in the app assembly script.

Update for notarization

---

releases/edge/mac-manifests.json
releases/edge/win-manifests.json

This PR changes where the released builds are hosted. We're seeing transient issues with Github release hosting that can be summed up by this issue: https://github.com/orgs/community/discussions/8535
I'm going to update `edge` and test them out before changing `stable`.

Change where released mac/win builds are hosted

---

.github/workflows/jacktriplabs.yml
macos/assemble_app.sh
macos/sign-stuff.sh

Allow the assembly script to create a temporary keychain for notarization so that it can run regardless of what the system keychain settings are.

Allow the use of a temporary keychain for notarization

---

docs/changelog.yml
src/jacktrip_globals.h

Given the discussion in #784, this preps for release of 1.6.6. 
Linking to the high-level plan laid out by @ntonnaett for next steps.
https://github.com/jacktrip/jacktrip/discussions/784#discussioncomment-4029512
We should leave this up for people to comment on across time zones.

Bump to 1.6.6 and update changelog

---

src/gui/vsDevice.cpp

We're getting an error with the 1st call because it's sending a float
```
json: cannot unmarshal number 99.00000095367432 into Go struct field .captureVolume of type int
```

Send capture volume as int

---

src/Regulator.h

remove extraneous call to readSlotNonBlocking in Regulator.h virtual void readBroadcastSlot, leftover lint from initial broadcast method for bufstrategy 3 (PLC)

remove extraneous call to readSlotNonBlocking in Regulator.h

---

macos/entitlements.plist

The updater code makes use of regular expressions - functionality provided by pcre2 which uses a just in time compiler to work its magic. This doesn't seem to be allowed by default in a hardened runtime anymore. We need to explicitly add a jit entitlement when signing.

Fix updater crash on Ventura

---

docs/Build/Linux.md

adding to User guide for Ubuntu and Fedora

Adding dependency libqt5websockets5-dev and qt5-qtwebsockets-devel

---

src/Regulator.cpp
src/Regulator.h

mNextPacket is used to provide a memory barrier to ensure that all write operations performed by the Regulator thread (to the transfer buffer) will be visible to the jack callback thread that pulls packets

Adding release-acquire ordering on the Regulator pull packet queue

---

src/UdpDataProtocol.cpp

Fixes https://github.com/jacktrip/jacktrip/issues/648
I don't claim to understand the comment, but this conditional for Windows causes it to hang for 10 seconds when trying to establish a connection to a hub server. Sadly, 10 seconds is also the amount of time that the hub server waits to receive the first datagram from client. This means that Windows clients are always in a tight race to establish a successful connection in time.
I believe this in particular happens when an IP address is used, causing QHostInfo to perform a reverse lookup, and there is no reverse lookup entry found for it. Windows just seems to deadlock for 10 seconds what that happens.
If this code is good enough for JackTrip.cpp to use when establishing the initial TCP connection to a hub server, it should be good …

Fix for client connection failures on Windows

---

src/AudioInterface.cpp
src/AudioInterface.h
src/RtAudioInterface.cpp
src/gui/Settings.qml
src/gui/virtualstudio.cpp

Handles https://app.asana.com/0/1203374736990005/1203374736990008/f. Removes `(default)` from the device lists and instead "pre-selects" that device by moving it to the top of the list. Additionally, it does not allow the user to proceed if there are no input or output devices.
This should not affect classic mode.

Remove (default) from Device Lists in Virtual Studio Mode

---

docs/changelog.yml
src/jacktrip_globals.h

Let's release 1.6.7 with the updated windows networking code, classic mode meters, and Non-ASIO devices on Windows

Change version to 1.6.7 and update changelog

---

src/gui/virtualstudio.cpp

Should take care of https://app.asana.com/0/1200778084029081/1203387632317029/f
I'm not sure if it makes the issue completely go away but at least on my Windows machine the rendering performs much better on resize. (I also don't really understand what Qt is doing internally here to know why this makes a difference).
I don't think this is an urgent enough fix to warrant trying to squeeze it into 1.6.7. It can wait until after the current release is done.

Fix Window Resize Rendering

---

src/gui/virtualstudio.cpp

Prior to this change, if a new subscriptions was created for a (private) studio and the "Refresh" button was clicked in-app, the new studio would show up under the "Public Studios" list. This was due to the `VirtualStudio::refreshStudios` function updating the list of studios but not the list of subscriptions, so the app would (incorrectly) by default categorize the newly subscribed studio as public.
These changes cause the subscriptions to be updated. Additionally, calling `getServerList` was a side effect of `getSubscriptions`. However, I think it's better for each function to just do 1 thing without side effects, so I decoupled the two.

Fix for Newly Subscribed Studios Showing Up Under "Public Studios"

---

docs/changelog.yml
src/jacktrip_globals.h

We have a critical usability issue addressed by #830. We need to release the fix asap.
Merge 830 and then we'll merge this and release.

Bump version and changelog for 1.6.8

---

.gitmodules

The flatpak builds needed a JACK2 module provided by the shared-modules git submodule. Flathub provides pipewire's own jack headers now. I already removed the module from all flatpak manifests but forgot to also remove the git submodule.

Remove unused shared-modules git submodule

---

src/RtAudioInterface.cpp
src/gui/Browse.qml
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h

Fixes by disabling vsAudioInterface on browse and closing the audio session before saving or reverting so that emitted signals don't trigger unnecessary audio restarts. Also addresses blocked UI thread.
https://user-images.githubusercontent.com/5567285/206810570-8a5defcd-cb82-4e87-a4e5-96b6f5448e42.mp4

Fix save/cancel hang

---

src/gui/vsAudioInterface.cpp

This is a bit of ifdef hell, but I'd love a review. 
There's more we can do, but I think one of the things going on with some of our segfaults being reported is either JACK or RtAudio being set without the corresponding necessary definitions.

Catching a few cases where neither JACK not RtAudio are available

---

meson.build

This makes sure that at least one audio backend is enabled when building with meson.

meson: error if no audio backend is enabled

---

src/gui/vsDevice.cpp

Sometimes when manually connecting to a studio with VS mode I get a "Connected" and immediate "Disconnected" screen, landing me back into the studio list view.
I did some troubleshooting to see why that's happening. Here's a brief log dump with print of `newObject` in `VsDevice::reconcileAgentConfig`:
```
step 1
JackTrip:startProcess before checkIfPortIsBinded(mReceiverBindPort)
JackTrip:startProcess before checkIfPortIsBinded(mSenderBindPort)
JackTrip:startProcess before setupAudio
Setting Up RtAudio Interface
...
step 4
UdpDataProtocol:run0 before Setup Audio Packet buffer, Full Packet buffer, Redundancy Variables
UdpDataProtocol:run0 before setRealtimeProcessPriority()
step 5
JackTrip:startProcess before mAudioInterface->startProcess
Initializing Faust plugins (have 4) at sampling rate …
```

Attempting to fix immediate disconnects

---

src/gui/virtualstudio.cpp

Fixes a bug introduced by #842 where network stats don't work under some conditions. I forgot to add the studio session id where I've already included the host IP and port number.

Fix Network Stats For Studio Starts

---

jacktrip.pro
src/gui/AudioInterfaceMode.h
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h

This **_begins_** work on moving from `#ifdef` of `RT_AUDIO` and `NO_JACK` to `if constexpr`. It uses that pattern to simplify some of the audio setup code and eliminate a couple of instances where VS mode could segfault.
It _does not_ bring that simplification to the underlying `AudioInterface`-based classes yet.

Address segfault due to ifdef hell with a move to c++17

---

src/Settings.cpp

Fix for Issue #495. Use separate arguments for input and output devices.

Create separate arguments for input and output devices

---

src/gui/virtualstudio.cpp

Use this additional `prompt=login` parameter to force a reauthentication after a user has pressed "Sign Out". Before this, when a user signed out and pressed the sign in button again, they would immediately redirect back to the desktop app without needing to log in via browser again.
https://user-images.githubusercontent.com/26987971/211953821-a90fd8b6-a863-4227-bb75-d87126bda1aa.mov

Reauthenticate After Sign Out

---

src/JackTrip.cpp
src/gui/Connected.qml
src/gui/virtualstudio.cpp
src/gui/vsServerInfo.cpp
src/gui/vsServerInfo.h

This should fix the "TCP Socket Error 19". I believe the root cause of this was:
```
newInterval = randomizer.bounded(0, newInterval);
```
which would pick a random number from 0 to `{newInterval}` which governs the sleep period between retries. This has some non-deterministic effects because it could exhaust all retries but not sleep for the full period we need to.
This also fixes a bug where you can start a studio that is shutting down which may have some bad outcomes. I handled this case with a text blurb:

Fixing TCP error upon connecting from desktop app start

---

.github/workflows/jacktrip.yml

So Windows signing has been silently failing since the PR @dyfer made and that I verified to move signing scripts out of `jacktriplabs.yml`. I moved the Windows signing process _back_ to a linux runner but still in the main build workflow, and it works great.
This should clear anything blocking the release of 1.7.0. (Pending an RC.2)

Fix windows signing

---

.github/workflows/jacktrip.yml

This should remove the `Node.js 12 actions are deprecated.` warnings in GHA

GHA: upgrade upload artifact action

---

.github/workflows/jacktrip.yml
jacktrip.pro
meson.build
src/JackTrip.cpp

#884 happened because of the missing QuickControls2 dependency. I'll open an issue downstream.
Edit: Also turns on ahead-of-time compilation of QMLs for the qmake build.
https://doc.qt.io/qt-6/qtquick-deployment.html#ahead-of-time-compilation

Add QuickControls2 dependency to Meson and Qmake, and enable ahead-of-time compilation of QMLs

---

src/gui/Browse.qml
src/gui/Connected.qml
src/gui/Studio.qml
src/gui/virtualstudio.cpp
src/gui/vsServerInfo.cpp
src/gui/vsServerInfo.h

Fixes a bug where video buttons are hidden from people who are not studio admins. Also renames/repurposes the `isManageable` button to `isManaged`, changing it's definition from "current user is a studio admin" to "is managed by JackTrip Labs." In lieu of `isManaged`, those variables have been replaced by `isAdmin`.
Owner:
Admin
Subscriber

Make Video Button Available to Non-Admins

---

.github/workflows/mkdocs-preview.yml

I wanted to have an option of previewing documentation changes even if I don't have access to configured environment with mkdocs installed.
This PR adds a GHA job that runs _only on PRs_ and _only on docs changes_, creating a static version of the docs. They are then uploaded as GHA artifacts. This allows previewing the changes from a static rendering, without the need to run mkdocs locally.
This still requires to download the archive, uncompress it and open `*.html` file(s) in the browser, it does not create an online-viewable preview.
Not sure if others will find this useful... any feedback is welcomed!

Preview docs in Github Actions

---

.github/workflows/clang-format.yml

Since clang-format action [is only checking files in `src`](https://github.com/jacktrip/jacktrip/blob/dev/.github/workflows/clang-format.yml#L13), then it should probably run only on changes in that directory.

GHA: run clang format only on changes in src

---

src/JackTrip.cpp
src/JackTrip.h
src/UdpDataProtocol.cpp
src/gui/virtualstudio.cpp
src/gui/vsDevice.cpp
src/gui/vsDevice.h

When in Virtual Studio mode, use a random bind port for the jacktrip client process.
This PR also fixes a bug with `checkIfPortIsBinded`. The `QHostAddress::Any` option is used to check if a port is bound on [both ipv4 + ipv6 interfaces](https://doc.qt.io/qt-5/qhostaddress.html#SpecialAddress-enum). So if the port of interest is only in use by ipv4, the exception will not be raised which allows the client to use the port despite if it's already in-use elsewhere. This is particularly problematic when its allowed to proceed, it kicks the older client out and lets the new client in. 
Also dumping this here because it was helpful to understand: https://learn.microsoft.com/en-us/windows/win32/winsock/using-so-reuseaddr-and-so-exclusiveaddruse

Use random bind port to avoid client collision

---

.clang-format
.pre-commit-config.yaml
docs/DevTools/Formatting.md

This adds a clang-format pre-commit hook and documentation. So nobody has to think about formatting anymore. However, it's opt-in.
In comparison to your IDE or using clang-format from your system. This uses the same clang-format version as our GHA = 13.

Add clang-format pre-commit hook

---

meson.build
meson_options.txt

With `meson configure -Dqtversion=6 -Dnovs=true` it doesn't build currently because of #925 . ~~But when fixing #925 with removing pow(), I get:~~
```
ccache c++ -Ijacktrip.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++17 -O2 -g -isystem/usr/include/qt6/QtWidgets -DQT_WIDGETS_LIB -isystem/usr/include/qt6/QtNetwork -DQT_NETWORK_LIB -isystem/usr/include/qt6/QtGui -DQT_GUI_LIB -isystem/usr/include/qt6/QtCore -isystem/usr/include/qt6 -DQT_CORE_LIB -isystem/usr/lib64/qt6/mkspecs/linux-g++ -fPIC -D_REENTRANT -pthread -DWAIRTOHUB -DNO_VS -DNO_UPDATER -DQT_OPENSOURCE -MD -MQ jacktrip.p/meson-generated_moc_qjacktrip.cpp.o -MF jacktrip.p/meson-generated_moc_qjacktrip.cpp.o.d -o jacktrip.p/meson-generated_moc_qjacktrip.cpp.o -c …
```

Add qtversion option to Meson build

---

.github/workflows/jacktrip.yml

I think the current logic is broken for Qt 5.15.0-5.15.2, as seen here: https://github.com/jacktrip/jacktrip/actions/runs/4189642206/jobs/7266985031#step:12:29
It seems that `opensource-` in filename is added only for Qt `5.15.3` and up (but not for 5.15.0-5.15.2, and also not for 6.0.0+)

GHA: correct Qt download link

---

.github/workflows/jacktrip.yml

Not sure if I have to do anything about *Windows-x64-qmake-gcc-shared* and *Windows-x64-meson-msvc-shared*.

GHA: Update Qt to version 5.15.8

---

src/Settings.cpp
src/Settings.h
src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/main.cpp

Initial work to allow the GUI (standard mode) to parse command line options. Currently works for all required arguments, optional arguments (with a couple of exceptions), audio patching, and authentication options. This is all outlined in the --help screen.
If someone can test that this has no ill effects for VirtualStudio mode, that would be greatly appreciated. (It shouldn't do, but it would be good to test that deeplinks aren't affected.)

Parse command line for GUI

---

src/Auth.cpp
src/Auth.h
src/Meter.cpp
src/Meter.h
src/UdpHubListener.cpp
src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/qjacktrip.ui
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h
src/gui/vuMeter.cpp
src/gui/vuMeter.h

Use a couple of float arrays that only get reallocated if the number of channels changes. (And have a working buffer that is only reallocated if it needs to grow.) This should stop the meter code from churning through memory.
As an added bonus, there's now an option in the classic GUI to execute an external script on connection or disconnection.

Replace QVector in meter code 

---

src/gui/virtualstudio.cpp

When working on the input channels feature, I mistakenly commented out one more line than I intended to, resulting in the user's selection of output device not being respected.

Fix Output Device Selection Bug

---

src/gui/Settings.qml
src/gui/Setup.qml

Fixes a minor issue with the refresh devices button that causes the audio device in-use to get out of sync with the display on the device combo box. This happens because the underlying data model changes, though the selected index of the combo box stays the same.
To reproduce on MacOS MacBook Pro (with headphones):
1. Make sure headphones are plugged in
2. Open app, select `Apple Inc.: MacBook Pro Speakers`, then press save
3. Close app and restart app
4. Select `Apple Inc.: External Headphones`. When testing output, audio should go through headphones
5. Unplug headphones
6. Refresh Devices. Combo box should switch to `Apple Inc.: MacBook Pro Speakers` and testing output audio should go through computer speakers
7. Plug in headphones
8. Refresh Devices. Combo box should switch to `Apple …

Bugfix Refresh Button & Device Combo State

---

.github/workflows/jacktrip.yml

**To start**:
We ran into an issue where Github was caching the manifest files for multiple days. So we're moving them to files.jacktrip.org.
**What this PR does**: 
On release, github actions will now take the newly created and signed release artifacts, upload them to files.jacktrip.org, download the manifest files, update them with a new release that points to those artifacts, and upload the updated manifest files. 
This takes a lot of the manual work out of releasing with the auto-updater.
The last part of the process that is still manual is moving the signed artifacts over the this repo to replace the unsigned ones.
Again, none of this happens on this repo, as the secrets are not available.
**Coming soon**:
A separate PR (then release) to update the url the desktop app points to when …

Automatically release to auto-updater

---

docs/changelog.yml
src/main.cpp

JackTrip will now look at files.jacktrip.org for manifest files since Github caches don't update as frequently as necessary.

Point updater to files.jacktrip.org

---

src/AudioInterface.cpp
src/AudioInterface.h
src/JackAudioInterface.cpp
src/JackAudioInterface.h
src/JackTrip.cpp
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/Settings.h
src/gui/qjacktrip.cpp

I've taken the path of least resistance to fix this, but I think we need to rethink the constructor for the base AudioInterface class. Channel selection has no meaning when using JACK and passing QVarLengthArrays doesn't make a lot of sense here. I'd suggest it would probably be worth either having an overloaded constructor, or (possibly better) having the channel lists as member variables of the derived RtAudioInterface class instead. (And having the getter and setter functions defined as part of this class rather than the base class.)

Fix crash when using JACK

---

src/JackTrip.cpp
src/JackTrip.h
src/JackTripWorker.cpp
src/RtAudioInterface.cpp
src/Settings.cpp
src/Settings.h
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/qjacktrip.cpp
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h
src/gui/vsDevice.cpp
src/gui/vsDevice.h

Follow up to #904. We'd also like the ability of users to select which output channels they want to use. It includes channel selection but not channel configuration options like with input channels (e.g. mix-to-mono, etc.).
- If the device has one channel  in VS mode, only a "1" is available
- If the device has more than one channel in VS mode, only stereo pairs are included "1 & 2", "3 & 4", and so on. There is no "1" or "2" (or so on), options.
[6dc5de2](https://github.com/jacktrip/jacktrip/pull/953/commits/6dc5de2c35a11d25fdc7e4a508bf1af5871d80d6) also fixes some bugs pertaining to the order and default values of `JackTrip()` constructor parameters.
This PR represents the minimal functionality we would like at this time on the JackTrip Labs side of the project. Any future work on …

Select Output Channels

---

CMakeLists.txt
jacktrip.pro
meson.build
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsInit.cpp
src/gui/vsInit.h
src/main.cpp

Main has accumulated a lot of VirtualStudio specific code which, combined with all of the ifdefs being used, has made it a little hard to get a quick overview of what is happening at launch. This PR encapsulates a lot of the deeplink and instance checking code in its own class.
Couple of notes: I've left the author field in vsInit.h and vsInit.cpp blank because it's not really my code. If anyone knows who originally authored it, and could add their name there, that would be great. Also, is the code that checks for an existing instance of the program really only meant to be run under windows? And as always, if someone could test that deeplinks still work as expected, that would be great.

Clean up main

---

.github/workflows/jacktrip.yml

The `github.event_name = 'release'` check was failing because we never actually run our actions in response to a release being published. This fixes that problem. 
We _may_ reconsider enabling the `deploy_gh` job on tagged commits and instead run it only on releases, but I don't have enough perspective as to what that would break.

Fix updater release scripts

---

docs/changelog.yml
src/jacktrip_globals.h

Including the JACK crash fix, return of the "JACK not installed" warning, and updated audio confirm text in VS mode.

Update version and changelog for beta 2

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h

Fixes some compiler warnings in builds not using RtAudio. To test and change flags with meson build system:
`meson configure -Drtaudio=disabled` or ``meson configure -Drtaudio=enabled` (in your build directory)

Fix Compiler Warnings When Building Without RtAudio

---

build-aux/flatpak/org.jacktrip.JackTrip.json
build-aux/flatpak/pypi-dependencies.json
build-aux/flatpak/requirements.txt
build-aux/flatpak/update_pip_deps.sh

Having the flatpak manifest in the build-aux directory let's Gnome Builder setup flatpak directly as a project configuration. This change makes it much easier to check and debug the flatpak build.

Adding build-aux directory for better integration in Gnome Builder

---

src/gui/virtualstudio.cpp

Follows up to and undoes #866. As a consequence of that pull request, first time users would need to log in again (for example, by re-entering their username and password) on the desktop app even though they had just done it through the web app by signing up for an account.
This PR undoes that requirement (46a35551ee02f2ba1fda87fa2deebce9115366eb) and redoes logout (01fb969608475bc6d5300ec6ad8c5fa14e74827b) by navigating to the user logout URL as explained [here](https://github.com/jacktrip/jacktrip/pull/866#issuecomment-1379713455). After pressing the logout button, the user is redirected to the app homepage. That may be good enough, or we might want to design a better dedicated logout landing page specifically for the desktop app.

Improve Sign In For First Time Users

---

src/gui/qjacktrip.cpp

Perform IP address check when showing the standard GUI for the first time rather than on creation. (It's not required if only using VS mode.)
This is an alternative to #964 that should solve Norton warnings if only using VS mode, while retaining IPv6 support.

Only check IP address if loading standard GUI

---

src/gui/qjacktrip.cpp
src/gui/qjacktrip.h

Realised when looking over the IP check code that there's an assumption that an IPv4 address will always be available. This allows the code to report an address when on an IPv6 only network.

Allow IP check to work with IPv6 only

---

src/Settings.cpp
src/Settings.h

The command line flags for setting the buffer size and sample rate were only available to the RtAudio backend. Making these flags available to all backends, let's us set the PIPEWIRE_LATENCY environment variable before the JACK client gets setup.
PIPEWIRE_LATENCY needs buffer size and sample rate. Getting the default values for these from JACK requires a JACK client. Instead of opening an ephemeral JACK client, ~~we require setting both buffer size (-F) and sample rate (-T) for setting PIPEWIRE_LATENCY instead.~~ we set the undefined value to the JackTrip's own default value.
PS: This also fixes -T segfaulting.

make buffer size and sample rate settable for Pipewire

---

src/RtAudioInterface.cpp

As it turns out, `QString::fromStdString(str).toStdString() != str` in the case of some special characters. We had some support tickets from people who had a `RØDE Microphone` and weren't able to use them. I don't fully understand why, since `Ø` is a utf-8 character which is the encoding that `fromStdString` and `toStdString` use. But this appears to fix the issue.
Tested by creating a virtual device with the "Audio MIDI Setup" with the name `RØDE Microphone`. I also tried it with other special characters (symbols, accented vowels, the `n` with tilde, etc). So maybe this won't fully fix the issue, but it does seem like it will support a wider range of devices.
https://user-images.githubusercontent.com/26987971/226728516-6f8981ea-2eb9-44e2-a421-5e8642c9abcf.mov

Fixes for Special Characters in Device Names

---

src/gui/virtualstudio.cpp
src/gui/vsInit.cpp

So the std::cout `VirtualStudio::show()` was somehow colliding with the socket and instead of the deeplink URL, the characters "SSL Lib" or "SSL L" were going across the local socket that checks for the existing instance of the app.
I switched it to qDebug since it's already in `virtualstudio.cpp`. Solved the problem.

Fix Windows deeplink when open

---

src/gui/AudioSettings.qml
src/gui/Settings.qml
src/gui/Setup.qml

I'm seeing that virtualstudio.cpp is reporting the correct device names and indices, but they are somehow not making it into the QML.
Moving these funcs into AudioSettings.qml seem to fix it.

AudioSettings should show the currently selected device

---

src/gui/virtualstudio.cpp

Must have forgotten to add these lines when working on output channels. This fixes the bug where channels other than 1 and 2 won't get saved - it'll always revert back - for output devices.

Save Output Channels Settings

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsInit.cpp
src/gui/vsInit.h

Get rid of complex nested lambdas so that the code is easier to read. Also adds a warning related to #979 and updates authorship of some files.
@mattahorton, I'm going to need your help testing this. (Deeplink functionality/instance checking on windows.) Cleaning up this code will hopefully help us to find and fix the root cause of #979.

vsInit cleanup

---

.github/workflows/jacktrip.yml

We have mostly moved our Windows package management to vcpkg, but currently the msys2 repo and mirrors no longer have the version of msys2 that vcpkg wants to pull as a dependency for openssl.
This temporarily gets msys2 from chocolatey until [this PR](https://github.com/microsoft/vcpkg/pull/30546) is merged.

Temporarily get msys2 from choco

---

src/gui/virtualstudio.cpp

bufferStrategy 3 is better for hubserver, while 4 is better for clients
An alternative approach here would be to just eliminate 4 and make 3 behave differently depending on which mode jacktrip is running

In virtual studio mode, always use bufferStrategy 4 for loss concealment

---

src/Meter.cpp
src/Meter.h
src/Tone.cpp
src/Tone.h
src/Volume.cpp
src/Volume.h

It turns out that it is unsafe to include multiple faust-generated C++ files in the same object. They contain multiple symbols which use the same name, including APIUI and #ifdef statements. Mixing these together leads to very unpredictable behaviour, including crashes.
In particular, I discovered the the vsAudioInterface class was including Tone.h, Meter.h and Volume.h, and each of those was including their own faust-generated c++ files. This was causing symbol conflicts in the generated object code. It's actually quite suprising that it only seemed to have a side-effect on Linux, and only in it "not working." I think we were just getting lucky.
I've reworked the Tone, Meter and Volume classes so that the faust generated c++ code is only used in their .cpp files. This ensures that each …

Fixing Play Test Tone button on Linux

---

src/Compressor.cpp
src/Compressor.h
src/Limiter.cpp
src/Limiter.h
src/Reverb.cpp
src/Reverb.h
src/StereoToMono.cpp
src/StereoToMono.h

For remaining ProcessPlugins..
We recently discovered it is unsafe to includes these in headers because it can lead to symbol conflicts.
See https://github.com/jacktrip/jacktrip/pull/1010

Moving faust-generated code out of header files

---

src/RtAudioInterface.cpp

since it is a subset of devices, not all of them.
This helps the tooltip make more sense, because otherwise you have no context of why the device you've selected is not low latency.

Changing "All Devices" for non-ASIO category to be "High Latency"

---

.github/workflows/jacktrip.yml

This PR adds an option to GHA so that the non-primary static build for a given platform will wait for Qt to be built, instead of failing and needing to be re-run manually.
I'm not sure this will work correctly for the tagged builds, but the worst that can happen is that the it will go back to the previous behavior (non-primary build failing and needing to be re-run).
You can see the [waiting behavior on my fork](https://github.com/dyfer/jacktrip/actions/runs/4888075686/jobs/8725397259#step:13:38), where the cache was not available. BTW I have since fixed the newline in posting.
EDIT: [when cache is immediately available, the step does not post anything and the build continues.](https://github.com/jacktrip/jacktrip/actions/runs/4889215207/jobs/8727545439#step:13:1)

GHA: add an option to wait for static Qt build

---

src/JackTrip.cpp
src/UdpDataProtocol.cpp
src/gui/Connected.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsDevice.cpp

There's a small downside here which is calling "refreshDevices" disconnects you from audio briefly. I guess this is because it's unsafe to reload the device list when it's wired up to meters + other things?

Refresh devices when opening the popup

---

releases/edge/mac-manifests.json
releases/edge/win-manifests.json
releases/stable/linux-manifests.json
releases/stable/mac-manifests.json
releases/stable/win-manifests.json
scripts/update_manifests.sh

Adding script to help automate this
Without this, everyone who has a release older than 1.8.0 has to upgrade twice to catch up. I think we should just manually keep these in sync for a few more months to smooth the migration process.

Updating manifests to match what is on files.jacktrip.org

---

src/gui/Login.qml
src/gui/Settings.qml
src/gui/virtualstudio.cpp
src/gui/vs.qml
src/gui/vsAuth.cpp
src/gui/vsAuth.h
src/gui/vsDeviceCodeFlow.cpp
src/gui/vsftux.qml

Follow up to #1037 
- Resolves issues with the back button appearing (and acting buggy) on the `vsftux` builds
- Removes the need for an extra sign up screen. This is done by attempting to log in (either through the code flow protocol or via the refresh token) whenever we switch to the login screen.
- If there's a refresh token stored, this doesn't initialize the code flow protocol. If this token is valid, the user shouldn't need to do anything to move to the next screen. If this token is invalid, this is gracefully handled by displaying an error message and initializing the code flow procedure.
Relevant tickets:
https://app.asana.com/0/1204518798614303/1204632412091470/f
https://app.asana.com/0/1204518798614303/1204632410251062/f …

Improvements and Fixes for Device Flow Code

---

src/gui/Settings.qml
src/gui/virtualstudio.cpp

Fixes a bug where the audio stream would stay open when switching from Virtual Studio mode to classic mode, a regression introduced by the "Code Flow" update. The reason is that the app tries to log in whenever it goes to the login screen (a UX requirement for the "Code Flow" feature), which then successfully re-authenticates using the existing token in the background, and automatically starts audio after successful re-login.
Note that with this, switching to classic mode and returning back to Virtual Studio brings the user back to "browse" rather than "login". This seems to be the easiest and cleanest way to fix the issue.

Cleanup Audio When Switching to Classic Mode

---

src/Meter.cpp
src/gui/AudioSettings.qml
src/gui/Connected.qml
src/gui/Meter.qml
src/gui/MeterBars.qml
src/gui/qjacktrip.qrc
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

I discovered that the volume meters in virtual studio mode were using about 3x the CPU versus volume meters in classic mode. These changes bring them in line with each other.
For more context: I created a stable test case and measured that JackTrip command line was using about 5% of a CPU core. JackTrip running in classic mode was using about 10% of a core, and JackTrip running in virtual studio mode was using about 20% of a core. This was all with the same traffic, settings, etc. I narrowed the bulk of the CPU use down to the volume meters and made various optimizations to avoid the performance penalty.
There are several changes in here, most of which probably doesn't make a huge difference. The most impactful change seems to be using a ListView in the QML but rather two fixed channels. …

Optimized performance of virtual studio volume meters

---

src/gui/AudioSettings.qml
src/gui/Connected.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

We currently detect and report these in Classic Mode (albeit with a cryptic warning message), but we don't currently say anything in Virtual Studio Mode, so the interface ends up telling someone their "connection quality is excellent" (for example) despite having regular outages and bad audio resulting from it.
This happens pretty much continuously if you are using WIFI, for example. So it's a great way to quickly identify root cause of audio issues caused by that, like forgetting to turn off WIFI and think you are using Ethernet when you actually are not.
Also updating clip indicators to use object variables instead of context properties

Let people know when they experience a network outage

---

src/Analyzer.cpp
src/JackTripWorker.h
src/Meter.cpp
src/UdpHubListener.cpp
src/gui/virtualstudio.cpp
src/gui/vsDevice.cpp
src/gui/vsDevice.h
src/gui/vsDeviceCodeFlow.h
src/gui/vsPing.h
src/gui/vsPinger.h

Otherwise, it's possible that the timer callbacks could be called while or after things are being deleted, which causes bad things to happen.

Ensure that QTimer objects are stopped before destruction

---

.github/workflows/jacktrip.yml
src/gui/Login.qml

In dark mode, you can't see the text unless you mouse over it.
This also replaces the button styling with less emphasized text links and makes "Use Classic Mode" show up even if it is not the first time run. Basically, always show "Use Classic Mode" if vsftux; othwerise, always show "Back" to go back to the Yes/No page.

This fixes an issue with text color of secondary login page buttons

---

src/main.cpp

This bug is now finally fixed via upgrade.
Note that the only people who would ever see this are the ones who still have the faulty Terminal application installed.

Add a friendly message to the empty window created by the Windows Terminal bug

---

src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/gui/AudioSettings.qml
src/gui/Connected.qml
src/gui/Settings.qml
src/gui/qjacktrip.cpp
src/gui/qjacktrip.h
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudioInterface.cpp
src/gui/vsAudioInterface.h
src/gui/vsAuth.cpp
src/main.cpp

I suspect this was causing a lot of problems on windows, but at a minimum this should significantly reduce Windows startup time and improves responsiveness when using RTAudio.
It now only scans interfaces when necessary, and not before trying to log into Virtual Studio (which caused what looks like login failures when there are actually audio interface issues). It also now logs whenever it is scanning devices, and prints out the results.
Eliminated duplicated code by caching the results of device scans.
Fixed some qml bugs/warnings with classic mode and eliminates rootContext()->setContextProperty() calls moving things into QObject properties.
Defer settings and audio initialization outside of QJackTrip constructor
There currently is a strange coupling between the QJackTrip gui and the …

Fixed issue with RTAudio scanning interfaces several times at startup

---

src/gui/virtualstudio.cpp

This is a regression from other recent changes. If you disable showing the audio settings at startup, and you connect to a studio without first manually opening the audio settings, the "Change Device Settings" dialog would have all empty dropdown lists.

Fixing bug with "Change Device Settings" dialog being empty

---

src/gui/Meter.qml
src/gui/MeterBars.qml

Adds a faint glow when bars are lit up, and also makes the bars scale responsively + fill in any gaps when the width changes.
https://github.com/jacktrip/jacktrip/assets/6201822/8d255365-b959-4c0a-bf31-1466b016c536

Updating styles of meter bars to be responsive

---

src/gui/AudioSettings.qml
src/gui/Connected.qml
src/gui/Settings.qml
src/gui/virtualstudio.cpp
src/gui/vsDevice.cpp

I think this fixes some of the level settings behavior across different parts of the app.
Fixes here include:
* When switching between prod/test, move app de-registration before revoking the authorization token. I noticed I had a lot of "stale" app devices registered so I don't think these was being cleaned up properly
* Changing input + output volume in Setup view should get reflected in the Connected/Settings views
* Changing input + output volume in Settings view should get reflected in the Connected/Setup views
* Changing input + output volume in Connected view should get reflected in the Setup/Settings views

Fixing device levels on registration

---

.github/workflows/jacktrip.yml
scripts/qt/qtbuild.bat

Giving up on trying to build dynamic qt inside of github actions
The runners available are just too small for it to finish within the 6-hour job limit. I tried using larger runners, but they don't seem to work at all for open source organization accounts, even if you enter payment info and have everything setup correctly.
We are going to just have to use manually built packages for Windows and OSX.

Adding openssl build to qt cache

---

src/gui/AudioSettings.qml
src/gui/Connected.qml

As a result of https://github.com/jacktrip/jacktrip/pull/1087, I think there's some jitter in the slider that occurs due to the precision in the way we interpret volume in the API as an int and the value interpreted by the slider components as a real number. This should fix it.

Fixing slider jitter due to int/float casting

---

src/gui/DeviceControls.qml

On light mode, I'm finding it hard to see that this has a background/is a button. This makes the shade a little darker.
Before:
After:

Making mute button darker

---

src/gui/WebEngine.qml

This disables the right-click menu on the webview which allows a user to navigate away and potentially break things.

Disable default context menu on right click

---

src/gui/virtualstudio.cpp

There's a QList crash here when `m_currentStudio = -1`

Handle crash by checking value prior to read from index

---

src/jacktrip_globals.h

I don't know if this is what we want it to be, I'm just changing it so it is not equal to `1.10.0` which is the latest released version

Bump jacktrip version for dev

---

src/gui/Settings.qml

From:
```
qrc:/vs/Settings.qml:167:13 Parameter "button" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
```

Fixing some QML syntax warning

---

.gitignore
jacktrip.pro
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/gui/qjacktrip.cpp
subprojects/rtaudio.wrap

qmake will still build using rtaudio 5.2.0, and care has been taked with the changes in JackTrip's source code to ensure backwards compatibility
Updated local variable names in RtAudioInterface.cpp to be more consistent, as previously they were using several different schemes in the same methods, which I found to be rather confusing.
Also fixed a bug with failing to build virtual studio support using qmake because the webenginequick module was not included in the project file

Updating rtaudio to 6.0.1 for meson builds

---

.github/workflows/jacktrip.yml
docs/changelog.yml
src/gui/AudioSettings.qml
src/gui/vsAudioInterface.cpp
src/jacktrip_globals.h

When an ASIO device is selected and you try to change to another (ASIO or non-ASIO) device on Windows, it would potentially cause a crash when using rtaudio to rescan devices while an ASIO device while already open.
Also removing a redundant call to validatedevices.
Bumping version to 1.10.1 for bugfix release

Fixing potential crash on Windows within the AudioSettings dialog.

---

.gitmodules
externals/Simple-FFT/LICENSE.md
externals/Simple-FFT/README.md
externals/Simple-FFT/include/simple_fft/check_fft.hpp
externals/Simple-FFT/include/simple_fft/copy_array.hpp
externals/Simple-FFT/include/simple_fft/error_handling.hpp
externals/Simple-FFT/include/simple_fft/fft.h
externals/Simple-FFT/include/simple_fft/fft.hpp
externals/Simple-FFT/include/simple_fft/fft_impl.hpp
externals/Simple-FFT/include/simple_fft/fft_settings.h
meson.build
meson_options.txt
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

so that git submodules are not required to create builds of JackTrip
Also added a `nofeedback` option for meson, so that JackTrip can be built without support for feedback detection, causing it to not use Simple-FFT at all.

Moving Simple-FFT into source tree

---

src/gui/DeviceControlsGroup.qml

You can click on some empty spaces and the click events will get registered into hidden components that are wrapped underneath some layers. This prevents that from happening.

Prevent propagation of mouse click events

---

src/gui/AudioSettings.qml
src/gui/ChangeDevices.qml
src/gui/DeviceControls.qml
src/gui/DeviceWarning.qml
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/qjacktrip.qrc

instead of an error about JackTrip being compiled incorrectly
Updated audio warning and error messages spread across 4 components to share a new common DeviceWarning.qml component, so that they look and behave the same way

Show friendly message when scanning audio devices

---

.github/workflows/jacktrip.yml

The 2.0.0-beta1 release artifact failed to automatically deploy to google cloud when it was released.
https://github.com/jacktriplabs/jacktrip/actions/runs/5790324332/job/15693619792
I believe this is the same problem I ran into working on the Qt build artifacts. There is a gcloud storage feature that breaks large file uploads on osx and linux runners.
Copying over the same patch I used to disable this feature, and will test it with the beta2 release

Fix for failed artifact deployment to google cloud

---

src/gui/AudioSettings.qml
src/gui/ChangeDevices.qml
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/vsAudio.cpp
src/gui/vsAudio.h

Added a new audio.scanningDevices property to help differentiate when audio is offline versus device scans. The device scans tend to be a lot slower versus when we are only restarting audio, so it probably makes sense to handle them differently.
Added a "Restarting Audio" message next to the device refresh buttons. This doesn't really apply as well to the change devices page since it does a reconnect and device scan when you change anything, and an extra refresh on top when you hit the refresh button.. But at least this is an improvement and perhaps change devices can be handled better in another PR..

Removing the screen flicker when you change audio channels or devices

---

src/AudioInterface.cpp
src/AudioInterface.h
src/JackTrip.h
src/gui/AudioSettings.qml
src/gui/ChangeDevices.qml
src/gui/DeviceRefreshButton.qml
src/gui/Settings.qml
src/gui/Setup.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudio.cpp
src/gui/vsAudio.h
src/gui/vsDevice.cpp
src/gui/vsDevice.h
src/main.cpp

after changing devices while connected to a studio
Fixed a bug where connecting to a studio from the audio settings setup screen could fail due to audio not being stopped in time. Updated VsAudio methods to add option for certain methods to block to support this and other fixes.
Reworked how device reconnect is handled from the change devices screen while connected to a studio. The JackTrip connection was previously being reset in parallel to audio validation, which could have caused things to not update correctly.
Refreshing devices while connected to a studio would cause device scans and validation in parallel to reconnect, which was even worse and caused crashes on Windows.
Fixing persistence of studio list filters to settings
Updating QML setters to check existing state before …

Making audio error/warning indicators work better

---

src/Analyzer.cpp
src/Analyzer.h
src/AudioInterface.cpp
src/Effects.h
src/JackTrip.h
src/UdpDataProtocol.cpp
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml
src/gui/vsAuth.cpp
src/gui/vsAuth.h

Removing VsQuickView from VsAuth since there seems to be no good reason for it to have visibility into that, and it breaks the pattern of VirtualStudio owning that exclusively.
Removed the authSucceeded and authFailed signals
from VirtualStudio because: (a) these were duplicates from VsAuth, (b) nothing used authFailed, (c) there was only a single qml connection really using
authSucceeded and it was easy to wire that up directly instead, since auth is a context variable, (d) having these in both places and meaning different things was very confusing and made it harder to grok and maintain
Replaced the firstLoad parameter in VirtualStudio::serverList with a m_firstRefresh class member, which is a lot easier to track and understand.
Changing use of m_refreshMutex to be a guard specifically …

Fixing deadlock conditions involving studio join

---

src/JackTrip.cpp
src/gui/virtualstudio.cpp
src/gui/vsAudio.cpp
src/gui/vsAudio.h

This eliminates having to rescan devices every time a connection to a JackTrip server is (re)established by reusing the scan results cached in the VsAudio class.

Use the VsAudio device cache when connecting to a JackTrip server

---

src/AudioInterface.cpp
src/AudioInterface.h
src/JackAudioInterface.cpp
src/JackTrip.cpp
src/RtAudioInterface.cpp
src/gui/DeviceWarning.qml
src/gui/vsAudio.cpp

Attemping to better handle the case where an audio interface rejects the buffer size that is configured. If VS audio settings is loaded (the default), it will reset the buffer size to the one used by the interface, and all seems to work ok. If you try to connect to a JackTrip server before this, it attempts to stop with a nice error message, but most of the time this still crashes. I tried to pinpoint why, but there are so many things done assuming this never changes that it may be a very hard task, which isn't worthwhile for just an edge case..
I also updated replaced DEVICE_WARN_LATENCY with DEVICE_WARN_BUFFER_LATENCY and DEVICE_WARN_ASIO_LATENCY to differentiate the two high latency scenarios for audio interfaces: the former is set if you have buffer size > 256 (2x default), and the …

Updates to handle bad audio interface buffer sizes

---

docs/Build/Linux.md
src/gui/AudioSettings.qml
src/gui/FirstLaunch.qml
src/gui/Settings.qml
src/gui/qjacktrip.cpp
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml
src/gui/vsAudio.cpp

Removing the loading screen because linux (possibly certain Qt versions?) were having problems with transitions that happen soon after a window is shown.
VS mode will now use default backend of RtAudio, if supported
Various other fixes for Jack audio and Linux things

Fixing startup screen for linux

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

The exit handler when clicking "x" on the window or force-quitting doesn't always leave property. I'm hoping that by exposing this `m_isExiting` we can do something with it over the web transport channel

Exposing isExiting over webchannel

---

src/gui/Footer.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsDevice.cpp
src/gui/vsDevice.h
src/gui/vsWebSocket.cpp
src/gui/vsWebSocket.h

Fixing:
* Clicking on certain spots in the Footer will "leave" the room (audio/video are still connected but the view changes)
* Refactoring how vsDevice creates and uses websockets
* Refactoring some methods within VsWebSocket
* Fixing leave sequence so it doesn't crash

Adding lock on stopJacktrip

---

src/gui/vsDevice.cpp

Otherwise local builds may not report the right version of the app.

Set version in constructor

---

src/gui/Connected.qml
src/gui/DeviceControlsGroup.qml

These settings do persist across joins so this ensures that self-managed studios will always show the full size controls

Remove minify button; always show full controls on self-managed

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsWebSocket.cpp
src/gui/vsWebSocket.h

Removing `m_connected` and `m_error` because I don't think those are reliable for the lifecycle of a given websocket connection. Instead we can inspect the [state](https://doc.qt.io/qt-6/qwebsocket.html#state) of the given websocket and use that to determine what should happen.
Also putting things inside of a `QScopedPointer` and adding a destructor

Rewriting vswebsocket class to check QWebsocket object properties

---

.github/workflows/jacktrip.yml
macos/meson_native_minversion_10.13.ini
macos/meson_native_minversion_10.14.ini
macos/meson_native_universal_10.13.ini
macos/meson_native_universal_10.14.ini

```
$ otool -l jacktrip | grep -E -A4 '(LC_VERSION_MIN_MACOSX|LC_BUILD_VERSION)' | grep -B1 sdk
minos 10.14
sdk 13.3
--
minos 11.0
sdk 13.3
```

Fix minimum version required for OSX builds (10.14)

---

src/gui/vsAuth.cpp
src/gui/vsAuth.h
src/gui/vsDevice.cpp
src/gui/vsWebSocket.cpp

This was causing everything to get reset, new device registered, etc. I'm honestly not sure if this works because it's so hard to retrigger the condition, but it seems like this should work..
When connecting to a studio, set enabled flag in local device settings cache. This should help alleviate the problem of it failing to send heartbeats when the initial connection attempt gets refused.
Retry establishing heartbeat webconnection when it fails
Disconnect device if the connection to server is lost
Adding a little more debugging output to help troubleshoot related problems in the future

Don't trigger auth succeeded sequence on token refreshes

---

src/gui/Settings.qml
src/gui/virtualstudio.cpp

Close the webchannel server so that `slotAuthSucceeded` doesn't error
Don't close timers, since these are not going to be restarted
Make clicking the button also cancel any settings changes and return you to browse screen

Fixing some bugs with switching between prod & test mode

---

src/gui/ChangeDevices.qml
src/gui/virtualstudio.cpp
src/gui/vsDevice.cpp
src/gui/vsDevice.h

Added an m_stopping flag in vsDevice to prevent multiple things from trying to trigger the stop sequence at the same time.
Cleaned up vsDevice JackTrip start/stop so that only startJackTrip() and stopJackTrip() are required. Eliminated other methods that just made everything more confusing.
Eliminated startPinger and stopPinger because there was no reason at all for these to be exposed outside of vsDevice, and no good reason for them to even exist as separate methods
Renamed terminateJackTrip to handleJackTripError, since that is what its purpose is. Although it probably could be eliminated since I've rewritten it to just be a wrapper around stopJackTrip.
Copying some changes from AudioSettings.qml over to ChangeDevices.qml

Fixing RC2 regression: changing devices disconnects you from studio

---

src/RtAudioInterface.cpp
src/gui/qjacktrip.cpp

Some device names returned by RtAudio, such as RØDE USB microphones, do not use valid utf8 character sequences. This ensures that the device names we get from RtAudio are converted to utf8 prior to comparisons, so they can still be used (even though their names will still look weird).
See also https://github.com/jacktrip/jacktrip/pull/974

Handle invalid device names more gracefully

---

docs/Build/Linux.md
meson.build
meson_options.txt

Added a buildinfo flag to set this manually
Adding help2man option to set a synopsis
From @umlaeute

Removing need to have git installed for meson builds

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h

I feel like I keep fixing the same bug, so I created a new method called resetState() which is now used by all the paths: Logout, Exit, Switch Test/Prod Mode and Switch to Classic Mode.
Decided that it's better to revert back the old behavior of stopping timers, but made sure they are all being stopped, and it sets m_firstRefresh to true so that the ones we want will get restarted later.

Fixing bug where switching to classic mode would break device stats

---

src/JackAudioInterface.cpp
src/gui/vsAudio.cpp

Jack docs say to use jack_free() not std::free()
Apparently, that matters!

Fixing for crash when using the JACK audio backend on Windows

---

docs/changelog.yml
src/AudioInterface.cpp
src/AudioInterface.h
src/Settings.cpp
src/gui/Settings.qml
src/gui/qjacktrip.cpp
src/gui/virtualstudio.cpp
src/gui/vsAudio.cpp

When using Virtual Studio or QJackTrip GUI on Linux, this sets the environment variable based on GUI settings, so there is no longer any need to set any environment variables or command line parameters for pipewire.
I think this should still work the same when running JackTrip from command line.
Also improving logic for rtaudio backend fallback

Set the PIPEWIRE_LATENCY environment variable with GUI on Linux

---

src/gui/virtualstudio.cpp

I think we've been trying to use [requestActivate](https://doc.qt.io/qt-6/qwindow.html#requestActivate) in place of [raise](https://doc.qt.io/qt-6/qwindow.html#raise) on the QWindow class to bring the window to the top of the screen, when they actually do different things.

Raise to Top Window on Deeplink

---

src/gui/vsDevice.cpp

Otherwise, it's possible to get "stuck" on a different server and not be able to reset and rejoin.

On app launch, set empty server ID

---

src/gui/virtualstudio.cpp

This ensures that JackTrip is brought back to the top after authenticating via code flow

Raise window to top after authenticating

---

.github/workflows/jacktrip.yml

Also bumping Windows dynamic build to 6.5.3 to pull in the latest Chromium updates. Note that Qt 6.5 has same system requirements on Windows as 6.2.
Removing dynamic builds using 5.15.10, since these aren't used and it consumes a lot of resources (and $$$) to create the 5.15.10 dynamic builds

Bumping qt version from 6.2.5 to 6.2.6

---

linux/README.md
src/Settings.cpp
src/Settings.h
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsAudio.cpp
src/gui/vsAudio.h
src/main.cpp

Added --classic-gui command line parameter to force classic GUI mode
Added qml6-module-qtquick-window to Linux README.md to account for broken dependencies on Debian
Fixed segmentation fault caused when destructing QNetworkManager during shutdown on OSX. Seems like Qt has bigger bugs underlying that since the only way I could work-around it was to leak it.

Added an error dialog displayed when required QML plugins are missing

---

src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vsDevice.cpp
src/gui/vsDevice.h

I think we need to bubble this up into the UI using the latency indicators

Adding network_outage flag to device json stats

---

src/Regulator.h

This changes bufstrategy 3 so that the packet queue is allowed to grow larger, irregardless of the time required for PLC predictions. I found that Realtek audio devices in particular seem to need much bigger queues.

Update to max target for PLC with worker thread

---

src/gui/ChangeDevices.qml

On the "Change Devices" screen, it's possible to click on buttons behind the view (like "Screen share" or "Leave")

Prevent mouse click through events

---

src/Regulator.cpp
src/Regulator.h

This also makes mSlots and mIncoming timer the same size (mNumSlots) and simplifies some of the shimming code when local FPP doesn't match peer
This also improves handling for the opposite case: when local FPP is larger than peer FPP. It uses a more robust approach that better accounts for out of order network packets (and sounds better).
Replace `mLostWindow` (which I believe was uninitialized?) with a search through newly arrived packets
Removing hardcoded sample rate of 48000

Fix PLC bug when local FPP is smaller than peer FPP

---

docs/Build/Linux.md
src/DataProtocol.cpp
src/DataProtocol.h
src/JackTrip.cpp
src/Regulator.cpp
src/Regulator.h
src/UdpDataProtocol.cpp
src/gui/vsDevice.cpp

Drop PLC stats measurements for first period since these are always very skewed by things starting up
Actually wait for DataProtocol to start running before starting audio rather than just sleeping for 1 millisecond and hoping that it works
When calculating PLC tolerance, accomodate poor audio interface clocks that have a wide range callback inconsistency (i.e. realtek), by using the max(pullStats, pushStats)
Allow PLC with auto headroom set to zero
Tick PLC pullStats for underruns and zeros
Add qt6-qtshadertools-devel to required packages for Fedora Linux

PLC startup and other optimizations

---

src/Regulator.cpp
src/Settings.cpp

This can happen on regular intervals for unreliable connections, such as wifi. Including it in the tolerance/jitter calculations simply makes latency excessively high for no benefits.
Fix to make "-q auto0" work again

Discard PLC auto measurements that exceed the maximum wait time

---

docs/changelog.yml
src/gui/virtualstudio.cpp
src/jacktrip_globals.h

Bumping version to 2.1.0-beta2

Fix for update channel not persisting when changed

---

.github/workflows/jacktrip.yml
docs/changelog.yml
src/Regulator.cpp
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/gui/virtualstudio.cpp
src/gui/vsAudio.cpp
src/gui/vsAudio.h
src/gui/vsDevice.cpp
src/jacktrip_globals.h

Fix 2.x virtual studio regression that starting forcing sample rate of 48000 even if the studio was configured to use a different one.
Use 44100 instead of 48000 when configuring an audio interface in virtual studio mode, since this seems to be supported by a greater range of devices.
Improve error message when an audio interface is disconnected on Windows computers.
Adding some extra sample rate checks and error handling
Fixing a benign bug in PLC code

Fix support for sample rates other than 48khz

---

build-aux/flatpak/org.jacktrip.JackTrip.json

Just to be in sync with the Flathub version.
https://github.com/flathub/org.jacktrip.JackTrip/pull/11

Flatpak: update to Qt 6.6

---

src/Regulator.cpp
src/Regulator.h

PLC tolerance is a receive buffer latency added to account for network jitter. This can be set manually using "-q #" where # is an integer in milliseconds; or, it can be set automatically using "-q auto"
The calculation of auto tolerance requires measuring the time in between receipt of each audio packet. The current approach takes a maximum of these measurements over a slice of time, and then takes the average of all these max measurements since the connection was first established. The longer a connection is established, the less it is able to adjust to connection quality, which can change over time.
We don't want auto tolerance to adapt too quickly though, because temporary abnormalities are normal. Changing tolerance too often can also have undesireable effects from the repeated …

Use exponential weighted moving averages for PLC auto tolerance

---

src/Regulator.cpp
src/Regulator.h

This updates the default behavior for "-q auto" so that it tries to automatically calculate a headroom value for you. You can still specify an explicit value, including 0.
The best value depends on the quality of your connection. When plugged into ethernet, on fiber Internet, 0 works great for me. Even cross-content. There's no need to add an extra 6 ms of latency (3 for server and 3 for client) when it doesn't improve quality.
Switching to wifi is a different story. Stdev goes up from about 0.1 ms to 0.6 ms, and about 3 ms headroom seems like a worthy tradeoff to minimize glitches. How about other connections? It's hard to say without being able to do a bunch of testing..
This branch combines the statistical auto tolerance calculation with observations of how it is actually performing …

Automatically calculate headroom for PLC

---

src/gui/FeedbackSurvey.qml

Attempting to make the user feedback form easier to dismiss after leaving a virtual studio
We've noticed that people often send "empty feedback" by clicking on the "Submit" button when no stars are selected and no comments are written. I believe the "No Thanks" button was being confused with the "Submit" button when people just wanted to quickly dismiss it. This should prevent that from being possible by having only one button, which submits if there is feedback and discards if there is none.
Hopefully having just one big button will also make it easier for people to quickly dismiss the dialog.
Nothing to submit:
Either a star selected or text in message box:

Attempting to make the user feedback form easier to dismiss

---

src/gui/virtualstudio.cpp

Ensures that audio device controls are always open when you first connect to a studio

Fix flickering of audio device controls when you reconnect after closing them

---

src/gui/Connected.qml
src/gui/DeviceControlsGroup.qml

Fixes issues with feedback detection
Don't show close button for self-hosted studios
Show close button when using Jack audio backend (managed studios)
Syncs height of area for "Back to Studios" button with create studio

More fixes related to collapsed device controls when connected

---

docs/changelog.yml
src/gui/vsAudio.cpp
src/jacktrip_globals.h

I suspect this may be causing sample rate issues with some Windows ASIO drivers, but don't have any way to reproduce or test it.

Use 48 kHz sample rate for audio testing interface

---

LICENSE.md
docs/About/License.md
src/gui/about.cpp

Windows builds of JackTrip using RtAudio include the ASIO SDK, which is owned by and subject to license from Steinberg Media Technologies GmbH
Updated LICENSE.md and about dialog

Update license files and about screen for compliance

---

src/AudioInterface.h
src/JackAudioInterface.cpp
src/RtAudioInterface.cpp
src/gui/vsAudio.cpp
src/gui/vsAudio.h

Some ASIO drivers seem to have issues when you open a stream using a different sample rate than they are currently using. They will start the stream but then immediately (and unfortunately, asynchronously) trigger an error for the sample rate change. It's unclear if this is a bug in RtAudio, or the driver implementation. An example driver that does this is "Yamaha Steinberg ASIO USB".
The net result is that audio just stops working, with no feedback why or what is happening.
This basically just intercepts the errors and triggers a device refresh when it happens, which works around the issue. It also ensures that an "Audio Error" warning will be triggered in the user interface for any audio interface errors that occur after starting the stream.

Work-around for ASIO drivers that have trouble changing sample rates

---

src/AudioInterface.cpp
src/gui/Browse.qml
src/gui/Permissions.qml
src/gui/Recommendations.qml
src/gui/Setup.qml
src/gui/Studio.qml
src/gui/virtualstudio.cpp
src/gui/virtualstudio.h
src/gui/vs.qml
src/gui/vsAudio.cpp
src/gui/vsAudio.h

Change virtualstudio.studioToJoin from a URL into a string, and parse all deeplink urls within handleDeepLinks.
Audio start for setup window is moved into joinStudio(), which waits until a studio is found. This has the added advantage of not found studios triggering an error right away, versus only after you click "Connect to Studio" from the setup window.
All deeplinks are now handled by joinStudio() signal fired after refreshing studios, versus just when on create studio page. This is just safer all around, and cleans things up a bit.
Made sampleRate a proper property of vsAudio
Removed dead code VirtualStudio::stopStudio()

Use studio's sample rate when testing audio before joining

---

docs/Build/Linux.md

to the commands for building on Linux. Some of these things are duplicated or pulled in as nested dependencies, but probably better to be thorough and ensure that you can run what you build.

Adding all the Ubuntu Qt6 dependencies for runtime

---

docs/changelog.yml
src/Regulator.cpp
src/UdpDataProtocol.cpp
src/jacktrip_globals.h

So that it only logs to console once per gap rather than every 30ms
Also replacing local variables and constants for 30ms with a new global gUdpWaitTimeout

Adding throttle for UDP waited too long errors

---

src/gui/DeviceControlsGroup.qml
subprojects/packagefiles/rtaudio-coreaudio-stream-channels.patch
subprojects/rtaudio.wrap

Patching RtAudio bug where OSX users of some audio devices with high channel counts (including RME) could experience garbled audio
Also hiding "Devices" label when Jack audio backend is selected

Use correct number of channels for the selected CoreAudio stream

---

src/Regulator.cpp
src/gui/vsAudio.cpp

I added this to the blacklist in https://github.com/jacktrip/jacktrip/pull/1088 but it seems to have gotten lost. Possibly removed by accident during a refactor?
Also fixing a crash when using -I option with PLC when connection fails

Blacklisting Generic Low Latency ASIO Driver

---

docs/changelog.yml
src/gui/Setup.qml
src/gui/vsDevice.cpp
src/jacktrip_globals.h

I believe this was causing bogus data to be sent at startup, causing strange connection statusus when it should have been "Measuring"
Don't start vsPinger for self hosted studios. This was causing an error about not having an auth token
Stop audio before starting to connect to a studio from setup screen. I'm not sure but this could have been causing the deadlock during window state transitions.
Bumping version and changelog for 2.2.3 release

Don't send ping data in heartbeats until after vsPinger has started

---

docs/changelog.yml
src/main.cpp
win/build_installer.bat
win/qt6-noguids.wxs
win/qt6.wxs

This is build of Mesa with llvmpipe. It is required by Qt when using the software OpenGL backend, which is used if OpenGL support on the system is missing or otherwise insufficient.
https://doc.qt.io/qt-6/windows-graphics.html
https://docs.mesa3d.org/drivers/llvmpipe.html

Include opengl32sw.dll in the windows installer

---

docs/changelog.yml
src/gui/vsAudio.cpp
src/jacktrip_globals.h
win/qt6.wxs

See https://community.jacktrip.org/t/old-jack-crashes-jacktrip-on-windows/722
Old versions of JACK installed on windows causes crashes in any application that tries to open the client library. This bypasses the problem for the most part by only ever trying to open the JACK client library if it is explicitly selected as a backend (which is not the default, at least for VS mode).
Fix for install directory of opengl32sw.dll on windows
Bumping version to 2.2.4 pending release

Defer checks for JACK libraries until opening audio interface

---

docs/changelog.yml
src/gui/virtualstudio.cpp
src/jacktrip_globals.h

If you tried joining a studio that was still starting up, and were not an admin of the studio, it would immediately kick you out and ask for feedback. It should now sending you to the waiting room, and automatically connect you once the studio session is ready.
Only ask for feedback if you've joined a session
Immediately refresh studio list when you leave a session
Also bumping version for 2.2.5 release

Fix for joining virtual studios that are still starting up

---

docs/changelog.yml
src/JackTrip.cpp
src/Regulator.cpp
src/Regulator.h
src/gui/virtualstudio.cpp
src/gui/vsAudio.cpp
src/gui/vsAudio.h
src/jacktrip_globals.h

Adjustments for FPP differences are made at pull time rather than when packets are being pushed. This enables us to perform more targetted predictions (using more "truth" and having smaller "glitches") when packets are missing and peer's FPP is larger than our own.
Removing PLC Regulator worker thread. After optimizations made previously, there is no longer any benefits to using this versus running things inside the callback. At this point it was just dead code, not worth updating for these changes.
Updated calculation of pushStats (packets arriving from peer) to be calculated at pull time, and to use previously known timestamps to calculate deltas. The previous approach did not handle out of order packets, which could significantly skew the stats lower than they should be.
Optimized …

Updating PLC to run using peer instead of local FPP

---

src/gui/Studio.qml

The confirmation message was being truncated, I believe because it calculates the size for the tooltip area based on the text at initialization time.
Before:
After:

Fixing truncation of invite copied tooltip message

---

.github/workflows/jacktrip.yml
Dockerfile
meson.build
src/QtStaticPlugins.cpp

Make static qt6 builds with meson work on linux
Update base jacktrip/jack container image for CI to 1.9.22-20240505. This includes latest ubi-init base image patches (using 9.4-6)
Update container to use a static build of jacktrip with qt 6.5.3. This shaves about 59MB off the image size and removes unnecessary things that increase vulnerability risk.

Various qt upgrade related things

---

.github/workflows/jacktrip.yml
docs/changelog.yml
meson.build
src/gui/Recommendations.qml
src/gui/qjacktrip.ui
src/jacktrip_globals.h

Updating qt 6.2.6 to 6.2.8 for OSX builds
Added support for static builds of jacktrip using meson across all platforms
Now using qt 5.15.13 to create static "nogui" (CLI) release packages across all platforms, built using meson
Update buffer strategy options in classic mode for PLC buffer strategy consolidation
Various tweaks to vs mode recommendations screens
Updated changelog and bumped version for 2.3.0-beta2 release

Upgrading qt versions for various releases

---

docs/changelog.yml
meson.build
src/JackTrip.cpp
src/Regulator.cpp
src/Regulator.h
src/gui/vsAudio.h

The previous approach for calculating auto headroom was overly aggressive at increasing it, in particular counting instances where the packets never arrived and therefore couldn't be saved by a larger headroom value.
This approach only increases headroom when there were actual instances of packets skipped that would have not been skipped if the headroom was 1ms larger.
Allow headroom to grow up to value of long term max versus arbitrary 5ms max.
Updated push lastMin and lastMax and dsp elapsed stats to track values over an entire time interval rather than just the most recent window observed. This provides a more accurate picture for testing and comparing different approaches.
Don't advance mLastSeqNumOut unless we actual use it; otherwise, it could throw other things off.
Fixed bug in …

Updates for PLC variable headroom calculations

---

src/JackTrip.cpp

When I start jacktrip in P2P server mode on a Linux system without IPv6 support, jacktrip exits without any apparent error:
```
Verbose mode
Settings:startJackTrip before new JackTrip
Settings:startJackTrip before mJackTrip->startProcess
step 1
JackTrip:startProcess before checkIfPortIsBinded(mReceiverBindPort)
Stopping JackTrip...
JackTrip Processes STOPPED!
---------------------------------------------------------
step 6
jmain before app->exec()
```
The reason is that `JackTrip::checkIfPortIsBinded` tries to bind the UDP port for IPv4 and IPv6. It fails for IPv6, because the Linux system has no `ipv6` module loaded.
This patch adds a check for `UnsupportedOperation` errors into that method, so that failures to bind to an IPv6 port is ignored.
P.S.: That I don't see the proper "Could not …

Start P2P server on system without IPv6 support

---

src/UdpHubListener.cpp
src/main.cpp

This PR is a proposed fix for #1301. It introduces a signal handler that ouputs errors from `JackTrip::signalError` and `UdpHupListener::signalError` to stderr.
It also modifies the "*.debug=true" QLoggingCategory filterRule to only take effect if verbose output has been requested. (Which fixes my problem in #1302).

Improve error logging for cli application

---

docs/changelog.yml
src/Regulator.cpp
src/jacktrip_globals.h

For me, this shaves a few ms (7 to 5) off prediction times @ 512 without any degredation in quality that I can notice.
Without this @ 1024 the predictions take 28ms, which effectively renders it useless. With this change, they take about 13ms which makes it work ok.
ALSO: Bumping version and updating changelog for 2.3.0 release

Using only 1 packet in the past for PLC if peer FPP >= 512

---

src/Regulator.cpp

This can happen if a connection fails / no initial packet from peer

Fix crash in Regulator if destructed before initialization

---

src/UdpDataProtocol.cpp

This is a proposed fix for #1310. It checks that the UDP packet size would not exceeded the 2^16 limit.

Check UDP packet size

---

macos/meson_native_minversion_11.ini
macos/meson_native_universal_11.ini
src/gui/Recommendations.qml

As we grow, we've seen people trying to use lots of audio devices that are old and/or very poor quality. This causes lots of audio problems that are hard to diagnose and understand. Making stronger recommendations about devices that we have properly vetted will lead to more successful outcomes.
Also adding native files for OSX 11, which is required by Qt 6.5 and later.
Windows has extra message about ASIO
Other platforms

Make stronger recommendations about audio devices

---

.github/workflows/jacktrip.yml
docs/changelog.yml
src/jacktrip_globals.h

Qt 6.2.7 introduced a regression bug in WebEngine that breaks screen sharing. In particular, screen sharing freezes whenever the application window is completely hidden. Unfortunately, none of the latest Qt releases seem to have fixed this yet.
Bumping version to 2.3.1 and updating changelog for release

Reverting OSX update to use Qt 6.2.8

---

src/vs/vsAudio.cpp

I thought that we may just be able to add a warning to discourage it, but after implementing and trying it out, it's clearly not enough. Bad things happen when you select iphone microphone that go far beyond latency and audio quality.
See https://discussions.apple.com/thread/254349417?sortBy=rank

Ignore devices that look like iPhone microphone

---

src/vs/Browse.qml
src/vs/CreateStudio.qml
src/vs/SectionHeading.qml
src/vs/virtualstudio.cpp
src/vs/virtualstudio.h

No reason to require an extra button click during the getting started process. About 30% of new users are dropping off on this, likely because we show them too many other things to do before creating their first studio.
Merging getServerList() and getSubscriptions() into refreshStudios() and updating getUserMetadata() to call refreshStudios() after it gets user meta data. We had a bug where we were sending all these requests asynchronously and:
* getServerList relied on the results of getSubscriptions
* getSubscriptions relied on the results of getUserMetadata
If they didn't all finish in the desired order, bad things would happen. This ensures that they all run in order to properly enforce their dependencies.
Don't show message that you have no studios when it's loading.
Default filters …

Skip create studio button if you are member of 0 studios

---

src/vs/Browse.qml
src/vs/virtualstudio.cpp
src/vs/virtualstudio.h

It makes for a poor user experience when the list keeps jumping around, and we already have a button to manually perform a refresh (in which case it isn't so annoying).
Before it not only would refresh when not desired, it failed to refresh when you wanted it to (or you had to wait for it, which made things confusing with status changes). Now it should ensure a refresh happens immediately, whenever you navigate to the "browse" window.

Getting rid of the 5-second studio refresh timer

---

.github/workflows/jacktrip.yml
LICENSE.md
LICENSES/MIT.txt
win/build_installer.bat

ASIO requires a license from Steinberg (which JackTrip Labs has)
Don't include classic mode in signed JackTrip Labs builds for Mac and Windows
Clean up license docs to reflect latest updates
Fix for broken windows installer

Only enable ASIO for Windows in JackTrip Labs builds

---

docs/changelog.yml
src/Regulator.cpp
src/vs/vsDevice.cpp

Allow use of most recent packet arrived if it's the best option
Lower skipped packet threshold for increasing headroom from 2% to 1%
Only require two seconds in a row for the skipped packet threshold to be broken if current tolerance is less than packet duration * 2
Use realtime threads for UDP packet processing. I discovered this does help reduce glitches, at least on my MacBook. If the threads don't have high priority, any kind of meaningful CPU activity will cause a material delay on the arrival of packets.

PLC auto headroom tweaks to improve audio quality

---

src/Patcher.cpp

add 100ms sleep to Patcher::registerClient to fix timing race with JACK
this fixes a problem under pipewire
the issue affected hub patching, for example, a server with hub patch modes -p1, -p2 or -p4
when a second (or subsequent) hub client connected, its ports were not yet listed in jack_get_ports
100ms sleep does the trick, maybe it can be even less

add 100ms sleep to Patcher::registerClient to fix timing race with JACK

---

src/vs/Settings.qml
src/vs/virtualstudio.cpp
src/vs/vsAudio.cpp
src/vs/vsAudio.h
src/vs/vsDevice.cpp
src/vs/vsDevice.h

PLC (buffer strategy 3) has matured to the point where it no longer makes sense to support the older buffer strategies. Although they are interesting for testing and research, there no longer is any real world value.
However, it is very useful to allow one to adjust the balance between lower latency and higher quality. PLC provides different mechanisms to do that, but we haven't yet made them available outside of the command line.
Effectively, PLC supports three different modes:
1. Auto latency adjustment based on connection heuristics, with variable headroom added automatically ("-q auto", represented as a queue buffer length of -500) -- this is the default
2. Auto latency adjustment based on connection heuristics, with a fixed amount of headroom ("-q auto#" where # is number of ms, …

Replacing buffer strategy with new PLC settings in VS mode

---

docs/changelog.yml
src/UdpDataProtocol.cpp
src/jacktrip_globals.h
win/meson.build

I confirmed that this causes severe garbled audio problems for some Windows users. Not sure if it's a bug in Windows, or if some home routers simply can't handle QoS, but either way it sadly doesn't work.
Bumping version and changelog to 2.4.1 for bugfix release

Disabling qwave support for Windows

---

docs/changelog.yml
src/Regulator.cpp

If a connection has really low jitter, the tolerance calculated is usually less than the duration of two audio packets. It's a very small window that doesn't leave much room for out of order packets.
This allows auto headroom to increase more agressively, up until the total tolerance matches or exceeds the duration of two audio packets.
I think this reaches a cleaner balance faster than the previous iteration, and should yield a better overall experience for people with optimized connections.

Increase PLC auto headroom more aggressively when very low jitter

---

src/vs/AudioSettings.qml
src/vs/vsAudio.cpp
src/vs/vsMacPermissions.mm

I can't figure out how to re-prompt, but we can at least change the message + include a link to where to change it. Looks like this:

Show open privacy button when microphone permission denied on mac

---

.github/workflows/jacktrip.yml

macos-12 runners are deprecated and will be removed December 3, 2024

Upgrade MacOS GitHub Actions runners to 13

---

.github/workflows/jacktrip.yml

Also add sha tag to container for develop branch builds
base64: invalid argument --output
Usage:	base64 [-hDd] [-b num] [-i in_file] [-o out_file]
-h, --help     display this message
-Dd, --decode   decodes input
-b, --break    break encoded string into num character lines
-i, --input    input file (default: "-" for stdin)
-o, --output   output file (default: "-" for stdout)

Work-around for broken base64 on macos 13

---

CMakeLists.txt
meson.build
src/OscServer.cpp
src/OscServer.h
src/Regulator.cpp
src/Regulator.h
src/UdpHubListener.cpp

Updated logic for Regulator::setQueueBufferLength to handle both fixed and auto headroom.
Moved queue buffer update logging up to once per change versus once per client per change.
Added mAutoHeadroomStartTime to handle headroom calculation being started after initialization.
No need to moc oscpp headers. It just gives warnings since there is nothing to moc.

A few updates for osc server support

---

src/vs/virtualstudio.cpp
src/vs/vsAuth.cpp
src/vs/vsAuth.h
src/vs/vsQuickView.cpp
src/vs/vsQuickView.h

Should handle the cases of people leaving their app open for long durations (>24h) more robustly. Currently, we don't continuously refresh our access token (which expires after 24h) after the initial app login, so things may break if you try to use the app after it expires.
This handles a few more cases by adding a 
- periodic access token refresh timer with an interval of 3 hours, and
- an additional access token refresh event when the window is focused and the current token is at least an hour old
This should additionally handle the case where the device goes to sleep for >24hours and wakes up again (though the user would need to click on the window to focus it and refresh the token). Having that done automatically might be useful but can be done in a separate PR if we need it.

Refresh Access Token Automatically When Keeping App Open For Long Durations

---

src/JackTrip.cpp
src/JackTrip.h
src/JitterBuffer.h
src/Regulator.cpp
src/Regulator.h
src/RingBuffer.cpp
src/RingBuffer.h
src/vs/vsDevice.cpp

This seems to be a better indicator which allows it grow and adjust faster for bad connections, without having an adverse impact on good connections.
Adding latency stat for Regulator (use "-I 1" to see it). This is helpful because tolerance is a maximum, and not necessarily indicative of true latency.
Adding receive latency to vs device heartbeat

Prefer glitch count to skipped for increasing headroom

---

src/jacktrip_globals.h

Increase UDP wait timeout to 512ms, since people using 1024 buffer size are still too likely to run into this and experience drop-outs.
Why 1024 buffer size? People using DAWs etc who are collaborating online do not care about latency, and sometimes may need to use a very high buffer size to avoid CPU overload of plugins, etc.

Increase UDP wait timeout to 512ms

---

.github/workflows/jacktrip.yml
docs/Build/Linux.md
linux/Dockerfile.build
linux/README.md
meson.build
src/AudioInterface.cpp

Using docker container to create all Linux release builds. Added new Linux arm64 static and dynamic builds, and a Linux arm32 static build for old Raspberry Pi bridge devices.
Switching qAsConst instead of std::as_const since older compilers that we are still using do not support it
Disabling PulseAudio in Linux static builds since it brings in a bunch of extra dependencies and is very SLOW

Adding support to build for Linux using a Docker container

---

src/Regulator.cpp

When auto headroom is updated dynamically, it could cause a race condition where calcAuto() was called before any measurements were made (ctr == 0). This would cause a recording of "max" with a negative value (the reset() value of -999999.0). This is such a large (or small?) value that it corrupted the longTermMax rolling average for a long duration of time.
The result of longTermMax corruption is that tolerance would be reset to a minimum value equal to the duration of a single audio buffer. This resulted in audio received from the participant being very garbled until longTermMax was finally able to recover.
It's a pretty nasty bug. A bit hard to find and unwind, but the fix is pretty clear and obvious. I just added some extra sanity checks to calcAuto to ensure that max (and min) are …

Fixing longTermMax stats corruption in Regulator

---

src/Settings.cpp
src/gui/qjacktrip.cpp

Allow for a comma to be escaped with a backslash if it's part of an rtaudio device name. (Should fix #1363.)

Fix for audio devices that contain a comma

---

docs/changelog.yml
src/jacktrip_globals.h
src/vs/vsAuth.cpp

It actually was logging out by clearing the access token, but we were failing to also clear the new refresh token. So it would just immediately trigger the cycle to use the refresh token to get a new access token, effectively logging in again right away.
Clearing the refresh token on logout fixes the problem, but also best to stop the refresh timer (it will get started again after successful login).
Also bumping version and changelog for beta2 release

Fix bug preventing logout from virtual studio mode

---

src/vst3/resources/JackTripEditor.uidesc

Based on feedback, this helps clarify that the two knobs on the right are for controlling the plugin's output audio

Adding Output to plugin knob labels

---

src/vs/virtualstudio.cpp

this reverts the logic in VirtualStudio::connectToStudio except that it adds an extra check for the server host being empty. The first time you connect, this should always be empty, forcing it to wait for the websocket response. But it will not be empty for subsequent reconnects to the same studio, enabling it to not have to wait for a new websocket message.

Fix regression with reconnecting JackTrip audio during live session

---

.github/workflows/flatpak.yml
.github/workflows/mkdocs-preview.yml
docs/changelog.yml
linux/README.md
src/vs/Browse.qml
src/vs/vs.qml

Fix studio padding (or lack thereof) when browsing on Linux
I think these are more related to the use of newer Qt releases versus Linux, but since we pin to older releases on other platforms I'm only mentioning that in the changelog
I honestly don't understand why rearranging things in vs.qml fixes the display of the failed screen, but it seems to work..

Fix for display of failed message screen during startup on Linux

---

src/vs/Connected.qml
src/vs/DeviceWarningModal.qml
src/vs/Setup.qml
src/vs/WebEngine.qml
src/vs/virtualstudio.cpp

There was some weird back-and-forth between studioToJoin and currentStudio when someone went to device settings page before joining a studio. This leaves studioToJoin alone and defers setting currentStudio until we're switching to the connected page.
Allow additional webengine flags to be set via env, for debugging

Don't reset studioToJoin when going to the device settings page

---

src/vs/virtualstudio.cpp

I believe this works from just the VsDevice perspective - I've gotten the underlying jacktrip connecting to change to a new IP. However there's some competing web code that's clobbering the smooth transition because it thinks it's a leave event (technically true).

Support for changing host

---

.github/workflows/jacktrip.yml
meson.build

This should handle the build with libsamplerate as a system dependency.
WIP: There's still a logic error, because I needed to set required: false.

meson: support libsamplerate as system dependency

---

.github/workflows/jacktrip.yml
docs/changelog.yml
macos/meson_native_minversion_12.ini
macos/meson_native_universal_12.ini
meson.build
src/AudioInterface.cpp
src/gui/qjacktrip.cpp
src/jacktrip_globals.h
src/vs/virtualstudio.cpp
win/qt6-noguids.wxs
win/qt6.wxs

Note that this drops support for macOS versions:
* 10.14 Mojave
* 10.15 Catalina
* 11 Big Sur
The minimum required by JackTrip 2.6.0 will be macOS 12 Monterey

Bumping builds to start using qt 6.8.2

---

docs/changelog.yml
src/jacktrip_globals.h
src/vs/Connected.qml
src/vs/WebEngine.qml
src/vs/WebView.qml
src/vs/virtualstudio.cpp

Fixing regression where you get kicked out of a studio whenever there are websocket messages received
Fixing various conflicts with QML's property caching and a previous commit surrounding studioToJoin
Only emit currentStudioChanged when changes are made, versus every time we receive a websocket message
When there are changes to currentStudio, make sure we emit the signal before performing other actions, so that QML interface will have the latest values
Trigger reconnect if there is a server port change as well, not just if there is a server host change
Use QML to cache url property for web views, so that if currentStudio properties do change, it doesn't reset and kick you out
Bump version to 2.6.0-beta0 to differentiate from final release
Fix changelog for qt 6.8.2 update

Fixing regressions that kick you out of a studio

---

.github/workflows/jacktrip.yml

7zip is pre-installed on github runners
choco zip package availability is unreliable, see https://github.com/jacktriplabs/jacktrip/actions/runs/13216962345/job/36897944899

Always use 7zip on windows, since the choco zip package is flaky

---

meson.build

Use the `-n / --noname` option to ignore non-deterministric information, such as timestamps, in gzip metadata.
This is required for [reproducible builds](https://reproducible-builds.org/).

Ignore timestamps recording in gzip metadata

---

.github/workflows/jacktrip.yml
docs/Build/Linux.md
linux/Dockerfile.build
src/AudioInterface.cpp
src/AudioInterface.h
src/JackTripWorker.h
src/OscServer.cpp
src/OscServer.h
src/RtAudioInterface.cpp
src/UdpHubListener.cpp
src/UdpHubListener.h
src/vs/vsAudio.cpp

Adding support to save and print audio device latency for RtAudio. This value seems quite suspect, so only printing it out for now.
Use system libsamplerate for Linux builds

Adding osc endpoint to get latencies for connected clients

---

src/OscServer.cpp

It turns out that our golang OSC library doesn't support arrays

 Send OSC response for client latencies without using an array

---

src/JackTrip.h
src/vs/Connected.qml
src/vs/CreateStudio.qml
src/vs/vsDevice.cpp

Renaming recv_latency to client_buffer_latency
Removing some unnecessary access tokens now that we're using cookies

Adding stats for audio interface input and output

---

src/vs/AudioSettings.qml
src/vs/vsAudio.cpp

This makes it a lot easier to switch between mono and stereo without having to first find a specific channel (or pair). And not being able to change it when having a mono channel selected is confusing.
Also allow any two consecutive channels to be used, versus every other two consective channels (for example, allow "2 & 3" not just "1 & 2" and "3 & 4").

Always allow selection between mono/stereo/mixtomono when > 1 channels

---

.github/workflows/jacktrip.yml
src/AudioSocket.cpp

Bumping ubuntu-20.04 to ubuntu-22.04 for qmake static build, since 20.04 is no longer supported by GitHub
Disabling vs mode for Linux-x64-meson-gcc-shared-nortaudio build since ubuntu-22.04 has qt 5.13 (not sure how this worked before?)

Replacing qDebug() with cout for Audio Socket reconnect

---

.github/workflows/jacktrip.yml
win/qt6-noguids.wxs
win/qt6.wxs

I normally wouldn't want to do this, but it seems easier to manage the compatibility issues vs needed updates that haven't merged to main yet..

Temporarily reverting qt 6.8 upgrade for another 2.5.x release

---

src/RtAudioInterface.cpp
src/vs/FeedbackSurvey.qml
src/vs/virtualstudio.cpp

This allows us to preserve the previous state for feedback survey responses.
Cleaning up feedback survey messages by splitting more things out into different fields.
No need to rescan devices when reconnecting to a new server on session change.

Don't reset device warnings and errors when stopping audio

---

docs/changelog.yml
src/Regulator.cpp

PLC previously enforced a relatively low headroom cap, which prevented it from growing too large on poor quality Internet connections. We've found few people understand quality of service nor the implications of this. In this situation, I feel it's better to lean towards audio quality, forcing people to make adjustments to achieve low latency versus leaning towards low latency and frustrating people with audio distortion.

Allow higher latency when using PLC auto headroom

---

docs/changelog.yml
src/vs/virtualstudio.cpp

UserId is stored in settings, and may be non-empty before an authentication token is received. This can cause the studio refresh to fail, and the list to be empty.

Wait for authentication to finish before refreshing studios

---

.github/workflows/jacktrip.yml
docs/changelog.yml

I keep coming across crashes with backtraces pointing to `Analyzer::onTick`. Also, this feature never really worked all that well: I regularly hear complaints about it triggering when it shouldn't and I've also seen it not trigger when it should. I think it's best to just remove this until we have time to put more effort into it.

Temporarily disabling support for feedback detection in meson builds

---

docs/changelog.yml
src/jacktrip_globals.h
src/vs/ChangeDevices.qml
src/vs/virtualstudio.cpp

Don't trigger reconnect when server host or port changes. I think it's better to trigger this via webchannel from the user interface so that the switchover happens simultaneously. Otherwise, the audio audio would reconnect right away despite having a warning and delay in the user interface.
Bumping version to 2.6.0 since all this has grown to be a bit more changes than strictly "bug fixes"

VS Mode improvements to audio quality override settings

---

docs/changelog.yml
src/vs/vsAudio.cpp

i.e. if a device has two channels, it allows you to chose from:
1, 2, 1 & 2, 2 & 3
(even though there is no channel 3)

VS Mode shows too many options for stereo devices

---

src/AudioBridgeProcessor.cpp
src/AudioBridgeProcessor.h
src/AudioSocket.cpp
src/AudioSocket.h
src/SocketServer.cpp
src/auv2/JackTripAU.cpp
src/vs/virtualstudio.cpp
src/vst3/JackTripVSTProcessor.cpp
tests/audio_socket_test.cpp

Creating a static QApplication and using QThread's EventLoop with signals and slots doesn't seem to work well in the context of plugins that can be loaded and unloaded dynamically.
In particular, I encountered some problems with Windows VST hosts where the first plugin you create works OK. But if you delete it and then create a second one, it locks up. It appears that there is some static flag getting set deep in QThread's EventLoop processing that basically just makes all threads exit.

Updating AudioSockets to eliminate dependency on QApplication

---

src/Regulator.cpp
src/RtAudioInterface.cpp
src/RtAudioInterface.h
src/vs/ChangeDevices.qml

Requiring a skipped packets that exceeded tolerance by less than past millisecond was kind of arbitrary, and we want to start preferring quality over latency whenever auto is enabled.
There is an edge case where if someone has sustained packet loss (say 1%) due to a really bad connection, it's going to keep bumping headroom until it hits max allowed. But that seems quite rare and if it is the case, they can always use the slider to adjust.
Updated max headroom calculation to use 10ms greater than the last good packet used, as opposed to a fixed value of 100ms. That was also quite arbitrary. This is perhaps slightly less so?
Ensure that we don't log in Regulator unless gVerbose is set (-V). Some of these happen inside the audio callback thread, which is one place you should never log …

Only use glitches for increasing auto headroom

---

src/Regulator.cpp

bugfix/plc-skipped-training started updating this whenever we had a valid packet but processed a glitch due to tolerance being exceeded. Burg seems to use this buffer even when the glitch flag is true, so I had thought that maybe we should keep it updated with the latest known value?
This reverts behavior to only update mXferBuffer when a packet is not being processed as a glitch. It will stay the same value for any sequential glitch processing.

Don't update mXferBuffer when processing packet as a glitch

---

src/Regulator.cpp
src/Regulator.h

We previously would never increase auto headroom by more than 1ms for every 2 second interval.
This patch allows auto headroom to increase more rapidly, when we have skipped good packets that we could have preserved. It adjusts it by enough that tolerance would have covered all of the good packets we skipped, or by at least 1ms.
Don't count packet latencies during the warmup period. I'm also shortening the "warm up period" from 3+3=6 ms to 2+2=4ms, because 6ms seems a bit too long to wait before it starts making adjustments.

Accelerate increases to auto headroom when we know it will help

---

win/jacktrip-bundle.wxs

since other programs may be using it

Don't uninstall the Visual C++ redistributable

---

.github/workflows/jacktrip.yml
docs/changelog.yml
src/jacktrip_globals.h

Signing seems to have randomly stopped working, despite zero changes. Even re-running the same builds that worked before has started failing. Maybe it has something to do with using the workspace directory versus the path from ssl.com's [example here](https://www.ssl.com/how-to/how-to-integrate-esigner-cka-with-ci-cd-tools-for-automated-code-signing/)
Bump version to 2.7.1-beta2 to test upgrades

Try using runneradmin path recommended by ssl.com for CKA
