- src/JackAudioInterface.cpp
- src/JackAudioInterface.h
> Typos - fixes #33

- INSTALL.txt
update a few commands, tested on Ubuntu 18.04
> Update Linux install commands

- CHANGESLOG.txt
> Revert "corrected my RtAudio misinformation"

- CHANGESLOG.txt
1.2 description updates, prior to tagging
> 1.2 description updates, prior to tagging

- src/JackTrip.cpp
- src/JackTrip.h
- src/UdpDataProtocol.cpp
- src/UdpDataProtocol.h
- src/UdpMasterListener.cpp
- src/UdpMasterListener.h
> Remove deprecated dynamic exception specification

- .travis.yml
get travis to do the deed on dev branch
> travis -> dev

- src/UdpDataProtocol.cpp
- src/UdpDataProtocol.h
> Revert "aaron to qjacktrip"

- src/AudioInterface.cpp
- src/Settings.cpp
small commit to help enforce consistency on the printed messages.
> studying new -x

- meson.build
Same as #142 but with those added files of dev branch.
> Fix meson in dev

- INSTALL.txt
On windows I believe 'which' is 'where'.
> win which -> where

- meson.build
Meson build was broken again in dev. This fixes it.
> Add AudioTester.cpp to meson build

- README.md
> Link to 1.2.1 installer

- CHANGESLOG.txt
created from JOS' git log --pretty=format:"%h%x09%an%x09%ad%x09%s"
> update to CHANGESLOG.txt in advance of beta.rc.1.3.0

- README.md
- documentation/documentation.cpp
> Merge main to dev

- CHANGESLOG.txt
- src/JackAudioInterface.cpp
- src/Settings.cpp
- src/UdpHubListener.cpp
- src/UdpHubListener.h
- src/jacktrip_globals.h
Had to manually resolve a bunch of conflicts. Needs more review on impact wrt new async listener.
@psiborg112 please review logic of return statements when client udp port fails check
> Merging hotfix-1.2.2 branch into dev by way of merge from main

- src/jacktrip_globals.h
Merge 1.3.0 beta branch to dev
> Beta.rc.1.3.0

- .github/workflows/jacktrip.yml
It seems I forgot to update Linux repositories, thus Linux build failed: https://github.com/jacktrip/jacktrip/runs/1745102411?check_suite_focus=true#step:3:194
EDIT: the Linux build in this PR passed
> GitHub actions: update apt before installing packages

- src/UdpDataProtocol.h
> Add missing #include <atomic>

- meson.build
- meson_options.txt
Small meson changes for the release
> Meson changes for JackTrip 1.4.0

- src/main.cpp
> Remove command name check code

- src/UdpHubListener.cpp
Regression when changing to dynamic allocation to appease MSVC.
> Fix use after free in the auth code.

- linux/jacktrip.desktop
> Add a French comment in the desktop file

- meson.build
> [Meson] Remove project version

- .github/workflows/meson.yml
- meson.build
- subprojects/packagefiles/rtaudio/meson.build
Sorry @dyfer! There were some flags missing. I forgot to pass the defines to the compiler. But no linking errors occured.
> Rtaudio subproject fixes

- macos/assemble_app.sh
- win/build_installer.bat
Needed for #294. (Doesn't include the actual static file list, just handles filename selection in the script.) Also give the windows script a little more flexibility in finding Qt and WiX. (Not tied to a specific version number.) And have the macos script search in some known locations for macdeployqt if it's not in the path.
> Have wix use the right file list for static win build

- .github/workflows/jacktrip.yml
- .gitmodules
- build
- jacktrip.pro
- src/JMess.h
- src/JackAudioInterface.h
- src/Patcher.h
I've tested locally on macOS and it seems to work. Build configuration updated for qmake only.
I've changed GHA builds for macOS and Windows to use weak linking. Linux build is unchanged.
If it works as expected, it would supersede #299
> Add the option to weak link with jack 

- CMakeLists.txt
- src/gui/qjacktrip.cpp
- src/gui/qjacktrip.ui
Incorporates and builds on the work of @dyfer in #324. Includes tool tips, corrected tab order, and buddy labels.
> Add backend selection to the UI

- .mailmap
This should clean up some git statistics. It might make it easier to contact the author of some work.
> Git Mailmap

- .github/workflows/jacktrip.yml
Unfortunately the deployment did not work... I think this is the missing part.
> Deploy fix

- .github/workflows/jacktrip.yml
> GHA: deploy on ALL tags

- src/gui/qjacktrip.ui
> added bufstrategy 3 (experimental) to UI choices

- docs/Install.md
- docs/index.md
This PR updates information on downloading JackTrip from GitHub releases, as well as provides a link to the latest dev builds. 
Open for any and all suggestions!
EDIT: should I mention anything about Jack for macOS and Windows? JT should work with all Jack versions now, but also does not require it, if one is satisfied with the default input/output. This is least tested on Windows. What should go in the install instructions thought?
> docs: update Install.md

- src/main.cpp
Fixs #355. No smart pointer needed.
> Fix stack use after scope

- linux/meson.build
- linux/org.jacktrip.JackTrip.desktop.in
> [Linux] Fix runtime icon

- src/JackAudioInterface.cpp
- src/JackAudioInterface.h
> don't unregister ports under pipewire, deactivate jack client instead

- docs/Build/Meson_build.md
> Document Ninja vs Meson

- src/JitterBuffer.cpp
> Fix sign compare in JitterBuffer

- docs/About/CHANGELOG.md
- src/jacktrip_globals.h
> Prepare for 1.4.0-rc4

- .github/workflows/flatpak-devel.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml.j2
- linux/org.jacktrip.JackTrip.metainfo.xml.in
This change fixes the flatpak-devel GHA to work with PRs.
Maybe this can also be the basis to generate a changelog in the future.
> Templated flatpak generation

- .github/workflows/flatpak-devel.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml.j2
> Remove SHA from flatpak GHA

- .github/workflows/jacktrip.yml
~~Added: upgrade Qt to 5.15 on macOS, see https://github.com/jacktrip/jacktrip/issues/393#issuecomment-917340168~~
~~possibly fixes #393, maybe #391?~~
AFAICT this fixes #391
> GitHub Actions: remove link time optimization for Linux/macOS

- .github/workflows/jacktrip.yml
This should fix #408
See https://github.com/jacktrip/jacktrip/issues/408#issuecomment-921339147 for more information
> Fix vcpkg rtaudio asio

- src/gui/qjacktrip.cpp
Updated a few defaults for the GUI that will work better for the vast majority of users:
* Enable auto jitter buffer
* Hub Client mode instead of P2P Client
> Updated a few defaults for the GUI

- src/jacktrip_globals.h
merge this & it's ready for the release!
> gVersion = 1.4.0

- macos/package/link.sh
- src/jacktrip_globals.h
Fixes #430
create /usr/local/bin directory if it doesn't already exist
> Fix for OSX installer failures

- macos/package/link.sh
- src/jacktrip_globals.h
I'm assuming a PR is needed to initiate this step, so here it is!
> merge 1.4.1 bugfix to dev

- src/jacktrip_globals.h
- subprojects/rtaudio.wrap
This needs to be approved by somebody but not merged, so I can do a fast-forward merge.
> Fast forward dev to main

- .github/workflows/jacktrip.yml
- CMakeLists.txt
- jacktrip.pro
- macos/assemble_app.sh
- meson.build
- src/JackTrip.cpp
- src/JackTrip.h
- src/JackTripWorker.h
- src/Settings.cpp
- src/Settings.h
- src/UdpHubListener.h
- src/gui/messageDialog.cpp
- src/gui/messageDialog.h
- src/gui/qjacktrip.cpp
- src/gui/qjacktrip.h
- src/gui/qjacktrip_novs.ui
- src/gui/textbuf.cpp
- src/gui/textbuf.h
- src/main.cpp
Please don't merge, just approve!
I will do a fast forward only merge afterwards.
> Dev to main for 1.4.2

- src/jacktrip_globals.h
> bump version and a couple other edits to jacktrip_globals.h

- src/jacktrip_globals.h
just keeping ahead of the game
> bumpDevTo1.4.4

- docs/changelog.yml
- src/Patcher.cpp
- src/Patcher.h
- src/Settings.cpp
- src/Settings.h
- src/UdpHubListener.h
- src/gui/qjacktrip.cpp
- src/gui/qjacktrip.ui
- src/gui/qjacktrip_novs.ui
- src/jacktrip_globals.h
Don't merge, only approve! Then we have a clean fast forward release.
> Release 1.5.0

- src/UdpDataProtocol.cpp
Fixes the last of the clazy issues. (#282 and #369)
> Fix use of detached temporary

- meson.build
- win/meson.build
Should fix #423 for windows when building with Meson. CI is my only test right now…
This also puts all windows related stuff in subdirectory `win`.
> Compile windows rc file (Meson part)

- src/main.cpp
> Fix PROCESSENTRY warnings

- src/JackTrip.cpp
Must have been introduced since a previous scan.
> Fix additional clazy warning

- .github/workflows/clang-tidy.yml
- .github/workflows/meson.yml
I've took the safe way described [here](https://github.com/platisd/clang-tidy-pr-comments).
This Github Action only checks changes of the PR itself. If it find's something in your PR it writes you a comment and might suggest a fix. I tested this on my fork. So you can see how it looks: https://github.com/ntonnaett/jacktrip/pull/6
> Add PR clang-tidy commenter

- .github/workflows/meson.yml
- docs/changelog.yml
It looks like the only thing missing for the release was to update the changelog.
> Prepare release 1.5.1

- src/gui/qjacktrip.cpp
- src/jacktrip_globals.h
> Fix limiter allocation in GUI

- src/PacketHeader.cpp
- src/UdpDataProtocol.cpp
- src/jacktrip_globals.cpp
- src/main.cpp
Change preprocessor definitions in an initial attempt to get JackTrip running on FreeBSD
> Initial attempt to get JackTrip on FreeBSD

- macos/assemble_app.sh
Sign the generated package if it isn't already and a certificate is provided.
> Update MacOS packaging script

- docs/Build/Linux.md
revised linux instructions for raspberry pi users who may be new to the build process and the terminal
> linux instructions for running two versions in parallel

- docs/changelog.yml
Forgot to update the changelog before release PR.
> Update changelog for 1.5.3

- .github/workflows/jacktrip.yml
- docs/Build/Linux.md
- docs/CustomJackServerName.md
- docs/changelog.yml
- jacktrip.pro
- mkdocs.yml
- src/JackTrip.cpp
- src/Regulator.cpp
- src/Regulator.h
- src/UdpDataProtocol.cpp
- src/jacktrip_globals.h
> Release 1.5.3

- src/gui/Settings.qml
Renames "Cancel" to "Back" in Visual Studio settings and closes #549
> Button rename

- jacktrip.pro
They were annoying me for a long time…
> qmake: remove wrong include paths

- .github/workflows/jacktrip.yml
- src/gui/Browse.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
Added a button at the top of the list that links to https://app.jacktrip.org/studios/create
> Create a studio button

- src/gui/Settings.qml
> Renaming buttons on settings page

- src/gui/Browse.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
This adds a button + menu that allows you to apply different studio filtering options. 
Screenshots:
> Adding studio filters to list view

- src/gui/Settings.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/main.cpp
This is not fully hooked up with the work in [this PR](https://github.com/jacktrip/jacktrip/pull/574), but this should add an option to select which channel to use for updates.
> Allow selecting update channel from settings

- src/gui/Setup.qml
Per https://github.com/jacktrip/jacktrip/pull/580/files/31eafd871d57c0b7e7c4f0f3c5f078c95c0ffebb#r878635443
> Remove extraneous windows error message

- macos/package/JackTrip.pkgproj_template
- macos/package/postinstall.sh
- win/build_installer.bat
- win/jacktrip.wxs
These changes open the JackTrip GUI upon finishing the installation via the installers.
> Open JackTrip post-install

- .github/workflows/jacktrip.yml
- CMakeLists.txt
- docs/Build/Mac.md
- docs/Build/Meson_build.md
- macos/assemble_app.sh
- scripts/hubMode/test_hub_mode_server_and_client.sh
- src/AudioInterface.cpp
- src/AudioInterface.h
- src/Auth.cpp
- src/DataProtocol.h
- src/JMess.cpp
- src/JMess.h
- src/JackAudioInterface.h
- src/JackTrip.cpp
- src/JackTrip.h
- src/JackTripWorker.h
- src/PacketHeader.cpp
- src/PacketHeader.h
- src/Regulator.h
- src/RingBuffer.cpp
- src/RtAudioInterface.cpp
- src/RtAudioInterface.h
- src/Settings.cpp
- src/UdpDataProtocol.cpp
- src/UdpDataProtocol.h
- src/UdpHubListener.cpp
- src/build
- src/gui/qjacktrip.cpp
Found via `codespell -q 3 -S ./faust-src -L ba, buss,numer,tipe`   
Fix clang-format-check
> Fix various typos

- src/jacktrip_globals.h
> bump version to release 1.6.0

- src/Regulator.cpp
- src/jacktrip_globals.h
> Fix plc min hist bug

- src/UdpDataProtocol.cpp
Fixes a regression in the network code.
> Fix UDP receive timeout

- linux/flatpak/org.jacktrip.JackTrip.Devel.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml.j2
- linux/flatpak/org.jacktrip.JackTrip.yml
Just some updates to the flatpak manifests.
> Flatpak update

- docs/Build/Linux.md
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml.j2
- linux/flatpak/org.jacktrip.JackTrip.yml
- releases/edge/mac-manifests.json
- releases/edge/win-manifests.json
- releases/stable/mac-manifests.json
- releases/stable/win-manifests.json
- src/Regulator.cpp
- src/UdpDataProtocol.cpp
- src/gui/Connected.qml
- src/gui/Login.qml
- src/gui/Setup.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/gui/vs.qml
- src/jacktrip_globals.h
Will be 1.6.1
please see https://github.com/jacktrip/jacktrip/discussions/629#discussioncomment-2987544
> Dev will be release 1.6.1

- releases/edge/mac-manifests.json
- releases/edge/win-manifests.json
Updating just `edge` first so I can do some sanity testing that things work before pushing it out to the masses
> Updating edge manifests

- src/gui/Browse.qml
- src/gui/Connected.qml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/gui/vsServerInfo.cpp
> Fetch regions to show human-readable location label

- src/gui/vsDevice.cpp
Removes warnings discovered by @ntonnaett mentioned in #692
> Fix unused warnings

- src/gui/vsDevice.cpp
We merged directly to main because it needed to be in main to work. This is bring that work back to dev.
> Bring build caching back to dev

- src/gui/Browse.qml
- src/gui/SectionHeading.qml
- src/gui/qjacktrip.qrc
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
**When all available Studios are filtered out**
**When there are no Studios at all**
> VS: Make UI usable when the studio list is empty

- src/JackTripWorker.cpp
- src/JackTripWorker.h
- src/Settings.cpp
- src/UdpHubListener.cpp
- src/UdpHubListener.h
- src/gui/qjacktrip.cpp
> Set bit resolution for hub server

- src/Auth.cpp
> Remove function deprecated in Qt 6.4.0

- src/main.cpp
Even though it's probably not the most practical idea without a separate update stream.
> Allow NO_VS to build without NO_UPDATER set

- docs/changelog.yml
- src/jacktrip_globals.h
There's a lot of good work we should start getting into people's hands. Let's cut a pre-release and start testing with it.
> Pre-release 1.6.5-rc.1

- src/gui/Settings.qml
- src/gui/Setup.qml
- src/tonedsp.h
I realized it was pretty trivial to show the input VU meters in the settings (thx to the handy `Meter` QML component) I'm currently hiding it for JACK because I can't seem to start my local JACK server and don't know what the behavior should be.
I don't know if we want this but I figured I'd throw the PR up
> Show input vu meter in settings

- docs/changelog.yml
- src/jacktrip_globals.h
> Bump version to 1.6.5

- macos/assemble_app.sh
- macos/sign-stuff.sh
Bringing @psiborg112's notarization changes from main back to dev
> Merge notarization changes into dev

- .github/workflows/jacktriplabs.yml
- docs/changelog.yml
- macos/assemble_app.sh
- macos/sign-stuff.sh
- src/jacktrip_globals.h
Finishing step 1 of [this release plan](https://github.com/jacktrip/jacktrip/discussions/784#discussioncomment-4029512)
> Release 1.6.6

- releases/edge/mac-manifests.json
- releases/edge/win-manifests.json
- releases/stable/linux-manifests.json
- releases/stable/mac-manifests.json
- releases/stable/win-manifests.json
Final step for releasing 1.6.6
> Update manifests for 1.6.6

- docs/changelog.yml
- src/jacktrip_globals.h
Also updates the changelog file
This release is the last step of the release plan we made [here](https://github.com/jacktrip/jacktrip/discussions/784#discussioncomment-4029512)
> Pre-release version 1.6.7-rc.1

- src/gui/Browse.qml
Displaying a button for "Reset Filters" if there are no studios in the list due to filtering.
Tackles https://app.asana.com/0/1201771974991986/1203230788085317/f
(Asana ticket says "Clear Filters", but Figma Doc shows "Reset Filters"; I went with the Figma Doc)
https://user-images.githubusercontent.com/26987971/200423769-1f66aeb8-47db-47c0-b60d-c3a1e87d8674.mov
Change wording for new users.
Tackles https://app.asana.com/0/1201771974991986/1203230788085313/f
> Studios Page FTUX

- releases/edge/mac-manifests.json
- releases/edge/win-manifests.json
Manifest changes to push 1.6.7-rc.1 to the edge channel
> Update manifests for 1.6.7-rc.1

- .github/workflows/flatpak-devel.yml
- .github/workflows/flatpak-release.yml
This updates the flatpak github action to the latest version. ~~Might fix #797.~~
> Update flatpak GHA to v4

- src/JackTrip.cpp
oops, sorry about missing that one
> Fixed uninitialized delete on disconnect when bufstrategy != 3

- .github/workflows/flatpak-devel.yml
- .github/workflows/flatpak-release.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml
- linux/flatpak/org.jacktrip.JackTrip.Devel.yml.j2
- linux/flatpak/org.jacktrip.JackTrip.yml
Updated some flatpak things and removed git submodules dependency. This also fixes #797
> Flatpak runtime update 22.08

- docs/changelog.yml
- src/jacktrip_globals.h
> Version + Changelog for 1.6.7 rc.2

- src/gui/Browse.qml
- src/gui/Failed.qml
- src/gui/FirstLaunch.qml
- src/gui/Login.qml
- src/gui/Settings.qml
- src/gui/Setup.qml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/gui/vs.qml
Fixes deep links not working. Especially when user has the app open and is on the browse page.
> VS: Deeplink Fixes

- src/gui/FirstLaunch.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
https://user-images.githubusercontent.com/5567285/205767039-b353dfb9-01f8-49f1-8c7e-ff1af3e30642.mp4
> Fix yes button on start screen

- src/gui/virtualstudio.cpp
- src/gui/vsDevice.cpp
- src/gui/vsDevice.h
- src/jacktrip_globals.h
> Support changing output volume via virtual studio API

- docs/changelog.yml
- src/jacktrip_globals.h
We've been treating our RC's like betas. Ideally, code should not be changing between RC and final version.
So this is a PR for 1.6.9 beta 1. 
We may still do an RC after testing but the goal will be to have no difference in the pre-release RC and the final 1.6.9 build.
> Update version and changelog for 1.6.9 beta

- docs/changelog.yml
- src/jacktrip_globals.h
Adds the "Video" button when connected in VS Mode
> Bump version/changelog to 1.6.9-beta2

- src/gui/virtualstudio.cpp
This is the original bug I ran into, where disconnects via web leaves my desktop client in a frozen state:
https://user-images.githubusercontent.com/6201822/211943441-034bffcf-94f2-4a1b-9dd8-1868ba7f3623.mov
I found that:
* After returning to the studios list view, clicking `Refresh List` persists the dark overlay because we aren't calling `emit refreshFinished(index);` prior to all possible `return`
* Even with the above, the studios list was not refreshing because we get stuck here:
```
QMutexLocker locker(&m_refreshMutex);
if (!m_allowRefresh || m_refreshInProgress) {
return;
```
I found that `m_allowRefresh` was set to false after disconnecting via web. This is [purposely set to false upon connect](https://github.com/jacktrip/jacktrip/blob/dev/src/gui/virtualstudio.cpp#L1047-L1052), …
> Call disconnect() to properly reset state on jacktrip process exit

- src/gui/Connected.qml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
Allows for a 1-click experience for starting a studio in VS mode.
Video:
https://user-images.githubusercontent.com/26987971/213007803-67f7abfa-1c12-4adb-89ef-c4b59c20f3c1.mov
Dark Mode:
> Updated Join/Start Experience

- docs/changelog.yml
- src/jacktrip_globals.h
Let's release 1.7.0 (changed from 1.6.9 according to conversation on Jitterbug list)
> Update version and changelog for 1.7.0 release

- src/gui/Connected.qml
Any chance we could squeeze this in to 1.7.0 or is it too late for that? (I don't mind if we push it to the next one)
https://user-images.githubusercontent.com/26987971/213780577-a8513bb9-4f73-4cf6-bc6d-d5e15deb4f44.mov
> Minor Wording Adjustments on Connected Screen

- src/gui/virtualstudio.cpp
Similar to #880. This also needs to be included - if not I believe Andrew's issue won't be resolved
> Another Emit Disconnected Needs To Be Wrapped

- docs/Build/Linux.md
- docs/Build/Meson_build.md
> docs: update linux package dependencies

- docs/Install.md
> Advertise Ubuntu PPA and Debian backports for latest releases

- src/gui/Browse.qml
- src/gui/Connected.qml
- src/gui/FirstLaunch.qml
- src/gui/Login.qml
- src/gui/SectionHeading.qml
- src/gui/Setup.qml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
This attempts to fix 2 leaks:
1. A memory leak built-in to DropShadow objects in Qt. Removed DropShadow entirely from the project.
2. A memory leak and segfault regarding Meter and Volume object pointers being reassigned haphazardly.
So far I have verified that one related segfault does not happen any longer on my development machine (macOS Ventura), and the `leaks` tool reports fewer leaks than before (though many seem built-in to Qt).
Edit: I also found the local source of the 50% volume issue and fixed it in this PR. It's a minimal change, and I don't think it requires the overhead of a separate PR.
> Attempt to fix a couple of memory leaks

- docs/Documentation/MkDocs.md
Here's a PR to test #899 in action :)
> Docs: add information about preview

- docs/changelog.yml
- src/jacktrip_globals.h
We'd like to get the video button fix in ASAP. Here is the prep for beta1 of 1.7.1
> Update version and changelog for 1.7.1-beta1

- .github/workflows/clang-format.yml
I [broke](https://github.com/jacktrip/jacktrip/actions/runs/4088259211/workflow) this in #901. Sorry!
> Fix clang-format check

- docs/changelog.yml
- src/gui/Settings.qml
> Add refresh button back to settings

- src/JackTrip.cpp
Pay no attention -- I'm using this to create some builds for debugging across platforms
> trigger GHA builds

- src/JackTrip.cpp
Might be worth having a Qt6 NO_VS build in github actions to check for these kinds of issues. (Sorry, I would offer to do it myself if I knew more about GHA.)
> Fix ambiguous call to overloaded funciton in Qt6

- src/gui/vs.qml
> fix warnings about new qml function syntax

- docs/changelog.yml
- src/jacktrip_globals.h
Releasing 1.8.0-beta1. Should merge #944 first
> 1.8.0 beta1

- src/gui/Setup.qml
- src/gui/virtualstudio.h
Changes the accept button text on the audio setup page if the app was opened from a link.
**Existing/Standard**
**Deeplinked**
> Change text on button when deeplinked

- .github/workflows/jacktrip.yml
> gha: add meson build with rtaudio disabled that errors out for warnings

- src/gui/Settings.qml
only show it if you're on the "Audio" tab
> Minor Fix for Refresh Button on Settings Page

- src/AudioInterface.cpp
- src/gui/Connected.qml
Adds warnings to the connected screen if devices are low latency (the screenshot below is only for visualization purposes; the devices I have wouldn't actually produce this warning)
> Add Warnings to Connected Screen

- src/gui/virtualstudio.cpp
This isn't pretty, but intended to be a low cost placeholder until we rework the flow a bit better
> Adding a simple link to create your first studio to VS login page

- src/gui/Setup.qml
Startup logs showing me this
```
qrc:/vs/Setup.qml:578:13: Unable to assign [undefined] to bool
```
> Fixing QML error on undefined boolean

- docs/changelog.yml
- src/jacktrip_globals.h
Preparing to release an update considering the large number of fixes we've merged in.
> Update version and changelog for 1.8.1

- .github/workflows/jacktrip.yml
> Revert #988

- src/JackTrip.cpp
- src/Regulator.cpp
- src/Regulator.h
- src/jacktrip_globals.h
also adding statistics on worker thread underrun when -I (iostats)
> Use realtime priority for regulator worker thread

- src/JackTrip.cpp
- src/JackTrip.h
- src/Regulator.cpp
- src/Regulator.h
Move regulator worker thread specific logic out of JackTrip class
Improve handling of regulator worker underruns
> Regulator worker thread cleanup

- src/Regulator.cpp
- src/Regulator.h
so that shimFPP can do its buffer size adjustment magic
> moving push to broadcast ringbuffer into pushPacket()

- src/gui/virtualstudio.cpp
- src/gui/vsDevice.cpp
Also fixing queue size setting for new bufferstrategy 4
> Make loss concealment (PLC) the default for virtual studio mode

- src/gui/vsDevice.cpp
I've found that this seems to be more reliable than 3ms
> Update PLC auto queue to use 5ms headroom in Virtual Studio mode

- src/gui/Connected.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
Looks like this:
https://user-images.githubusercontent.com/6201822/234994788-0cb3d77b-818f-4f4f-ae33-12ffef0b3a1d.mov
> Show error message when single studio limit is reached

- src/gui/AudioSettings.qml
- src/gui/Connected.qml
> Updating some tooltips, sliders and positioning for connected interface

- .github/workflows/jacktrip.yml
- linux/README.md
- src/gui/Connected.qml
Also a few minor tweaks to VS connected screen fonts and positioning
> Adding icons and basic README.md with instructions to Linux package

- src/gui/virtualstudio.cpp
- src/jacktrip_globals.h
Also bumping version to 1.9.0 to start building RCs
> Fix for broken output volume meter and monitor when using JACK

- src/gui/Login.qml
Switch from "Logging In..." to "Configuring Audio..." once user authentication is confirmed.
https://github.com/jacktrip/jacktrip/assets/26987971/e496a44f-4bff-461f-b6e3-08e2b86c6fd6
> More Informative Loading Message

- src/Regulator.cpp
- src/Regulator.h
- src/gui/virtualstudio.h
This appears to give a 2-3x performance boost
> Optimize PLC regulator performance by using double instead of long double

- docs/changelog.yml
Forgot to do this when bumping version
> Updating changelog for 1.10.0-beta1

- src/gui/Connected.qml
- src/gui/Settings.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
Requires #1035
Adds a popup notification when feedback occurs, and allows the user to disable it under advanced settings.
> Optionally Disable Feedback Detection

- docs/changelog.yml
- src/Analyzer.cpp
- src/Analyzer.h
- src/AudioInterface.cpp
- src/Compressor.cpp
- src/Compressor.h
- src/Limiter.cpp
- src/Limiter.h
- src/Meter.cpp
- src/Meter.h
- src/Monitor.cpp
- src/Monitor.h
- src/ProcessPlugin.h
- src/Reverb.cpp
- src/Reverb.h
- src/RtAudioInterface.cpp
- src/StereoToMono.cpp
- src/StereoToMono.h
- src/Tone.cpp
- src/Tone.h
- src/Volume.cpp
- src/Volume.h
- src/gui/virtualstudio.cpp
- src/jacktrip_globals.h
Push and pull buffers of samples rather than one at a time
Add buffer size to ProcessPlugin::init and other related code cleanup
> Optimize circular buffer for feedback detection

- src/gui/AudioSettings.qml
- src/gui/Connected.qml
I think this fixes some (but not all) of the errors in https://github.com/jacktrip/jacktrip/issues/1036
Also moving `Colorize` to not reference `parent` because that doesn't work in Qt6
> Addressing some QML errors

- src/gui/Browse.qml
- src/gui/Connected.qml
- src/gui/Failed.qml
- src/gui/FirstLaunch.qml
- src/gui/Settings.qml
- src/gui/Studio.qml
- src/gui/vs.qml
- src/gui/vsftux.qml
This should fix the remaining QML errors in https://github.com/jacktrip/jacktrip/issues/1036. My editor has a whitespace remover which touched a lot of other QML files but the relevant change is in `Connected.qml`
> Fixing connected view errors

- src/gui/messageDialog.cpp
- src/gui/messageDialog.h
- src/gui/messageDialog.ui
Makes it easier to see how often UDP waiting too long messages are being repeated, especially when coming from a single source. Also fixed the autoscrolling mechanism.
> Add timestamps to debug window

- src/JackTrip.h
- src/gui/qjacktrip.cpp
- src/gui/qjacktrip.h
- src/gui/qjacktrip.ui
Set some environment variables that connection scripts can rely upon.
> Script environment variables

- src/gui/virtualstudio.cpp
No new issues encountered from testing since beta4 release
> Updating new FeedbackDetection setting to be enabled by default

- .github/workflows/jacktrip.yml
This also lays some groundwork for upgrading static builds to qt6
> Updating some of the packages included in static qt6 builds for WIP

- .github/workflows/jacktrip.yml
- jacktrip.pro
- meson.build
- src/gui/virtualstudio.h
- src/gui/vsDevice.h
Removing all the logic for building qt static from source
New qt builds are provided by https://github.com/jacktriplabs/jacktrip-qt
> Switching to external qt builds for all matrix jobs

- .github/workflows/jacktrip.yml
- macos/JackTrip.app_template/Contents/Info.plist
- macos/assemble_app.sh
- macos/entitlements.plist
This also fixes the auto manifest updater (I think), broken by recent CI changes
> Attempting to fix broken macos package signing

- src/gui/Recommendations.qml
Also moving wired headphones to be the last, since unlike all the others that are "Recommended", this one is "Required."
> Obsessing with the getting started wording

- src/gui/Settings.qml
Our new layout doesn't do well on larger interface scales
> Reduce range of uiscale

- src/gui/Connected.qml
- src/gui/DeviceControlsGroup.qml
> Re-Add Feedback Detection Alert

- src/RtAudioInterface.cpp
- src/gui/ChangeDevices.qml
Fixing missing font size on VS change devices screen
> Fixing some regressions involving rtaudio5 support

- docs/Build/Linux.md
- docs/changelog.yml
Also updated build instructions for Linux
> Updated changelog for 2.0.0-beta2

- src/gui/WebEngine.qml
On windows, I notice that I can sometimes see the device selection view when it transitions
> Set background color

- src/gui/vsDevice.cpp
This fixes a small benign error found in logs:
```
Listening for deep link requests
SSL Library:  "Secure Channel, Windows 10.0.22621"
Log file location: "C:/Users/mike/AppData/Roaming/jacktrip/JackTrip/log.txt"
Successfully authenticated Virtual Studio user
User ID: google-oauth2|113630931127186968897
QWebChannel listening on port: 62647
Error: Error transferring https://app.jacktrip.org/api/devices/ - server replied:
Device not found. Creating new device.
```
The root cause was that `removeApp` occurs during logout and is asynchronous, so it relies on the `finished` slot callback to clear app settings. I'm finding that this callback never gets called which produces some inconsistent results. The next time you login, `settings.value(QStringLiteral("AppID"), "").toString();` evaluates to …
> Make removeApp synchronous in order to clear settings

- src/JackAudioInterface.cpp
- src/JackTrip.cpp
- src/RtAudioInterface.cpp
- src/RtAudioInterface.h
- src/gui/virtualstudio.cpp
> Improved handling of error messages from audio interfaces

- docs/changelog.yml
- src/gui/virtualstudio.cpp
- src/jacktrip_globals.h
Also fixing a small bug where logging out of Virtual Studio then immediately logging in again would break device network stats
> Updating version and changelog for 2.0.1 release

- .github/workflows/jacktrip.yml
- meson.build
- src/AudioInterface.cpp
- src/AudioInterface.h
- src/RtAudioInterface.cpp
- src/gui/AudioSettings.qml
- src/gui/ChangeDevices.qml
- src/gui/vsAudio.cpp
- src/gui/vsPinger.cpp
- src/gui/vsWebSocket.cpp
Fixes also a bug with compression of Linux manpage
Also printing backend names now instead of RtAudio API ids
> Build Linux tarball binary with support for ALSA backend

- src/Settings.h
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/main.cpp
This is very useful for debugging the audio receive queues
> Allow virtual studio to use -I stats command line parameter

- src/Analyzer.cpp
- src/Analyzer.h
I tried messing with the thresholds here but I got a little lost in the sauce there. This counter mechanism seems to work better empirically though.
> Use counter and trigger on consecutive detections to account for false positives

- src/Regulator.cpp
The plcUnderrun and plcOverrun stats were getting reset about 16 times per second, and -I was only reporting the values from the last interval
> PLC fix for drastic underreporting of glitches

- src/Regulator.cpp
This is a regression in 2.1.0-beta that happens maybe 1-10% of the time at startup and continues until you reset the connection.
mLastSeqNumOut was being used before it was ever set (as -1), and even worse used as an array index, causing uninitialized memory read. Suprisingly this wasn't crashing but just returning random results. If you got unlucky, it put things in a state where it continuously glitch/underrun, returning no audio.
This also fixes an unrelated regression without counting of underruns when they exceed MaxTimeout.
> Fix PLC regression causing no audio when connected

- .github/workflows/flatpak.yml
Update the flatpak-builder gha. Maybe this fixes our flatpak build.
> gha: update flatpak builder action

- docs/changelog.yml
- src/Settings.h
- src/jacktrip_globals.h
Also fixing a compiler warning with Settings.h when NO_GUI
> Bumping version and updating changelog for 2.2.0-beta1

- src/gui/DeviceControlsGroup.qml
- src/gui/close.svg
- src/gui/qjacktrip.qrc
Also fixing some bugs introduced in previous PR related to collapsing height to zero
Light mode
Dark mode
> Adding X button to close audio device controls drawer

- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
Also fixing various other bugs with deeplinks and refresh of the server list
> Fix for broken deeplinks when the studio doesn't match filters

- releases/edge/mac-manifests.json
- releases/edge/win-manifests.json
- releases/stable/linux-manifests.json
- releases/stable/mac-manifests.json
- releases/stable/win-manifests.json
> Updating the old manifest files for 2.2.1 release

- src/gui/virtualstudio.cpp
- src/gui/vsDeeplink.cpp
Deep links were failing on Windows about 5% of the time. Console showed the following messages when it happened:
Never ready to read
Not ready and no bytes available
It seems that QLocalSocket::flush() does bad things, and docs for it suggest using waitForBytesWritten() instead. That seems to fix the problem.
I also cleaned up some of the error handling, and made it support the format jacktrip:join/<studio_id> which is more comformant with the URI standard.
> Fix for unreliable deeplink handling on Windows

- .github/workflows/jacktrip.yml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
- src/gui/vsConstants.h
- src/gui/vsWebSocket.cpp
app.jacktrip.org => app.jacktrip.com
test.jacktrip.org => test.jacktrip.com
> Updating domain name for virtual studio endpoints

- .dockerignore
- .github/workflows/jacktrip.yml
- Dockerfile
- linux/container/README.md
- linux/container/jacktrip.service
- src/Settings.h
Uses jacktrip/jack base image built here https://github.com/jacktriplabs/jack-container
This replaces the old repo at https://github.com/jacktrip/jacktrip-container
Fixing compiler warning for guiEnabled in Settings.h
> Adding files for building a docker image

- src/AudioInterface.cpp
- src/gui/virtualstudio.cpp
> Updating help links to point to support.jacktrip.com

- src/gui/Browse.qml
- src/gui/Studio.qml
- src/gui/virtualstudio.cpp
- src/gui/virtualstudio.h
- src/gui/vsServerInfo.cpp
- src/gui/vsServerInfo.h
Cleanup and removing a few methods that are no longer necessary
> Updating "Manage" button when browsing studios to go to dashboard

- src/AudioInterface.cpp
- src/gui/DeviceWarning.qml
- src/gui/LearnMoreButton.qml
- src/gui/Recommendations.qml
- src/gui/qjacktrip.qrc
Updated audio warning indicators so that they are clickable again
> Adding learn more buttons to recommendation screens

- src/gui/Login.qml
> Update virtual studio ftux page to a be a little simpler

- .github/workflows/jacktrip.yml
It's currently missing README.md and other files due to a bad job name
> Fix for linux download zip missing files

- src/vs/CreateStudio.qml
Uses new create studio interface
> Use new create studio flow

- docs/changelog.yml
- src/vs/Login.qml
- src/vs/vsAuth.cpp
- src/vs/vsAuth.h
- src/vs/vsDeviceCodeFlow.cpp
- src/vs/vsDeviceCodeFlow.h
Assuming that DNS errors are caused by Internet connection offline and added special handling for that case
> VS Mode improved error handling for login screen

- src/vs/CreateStudio.qml
Fix to https://github.com/jacktrip/jacktrip/pull/1327#issuecomment-2332501646 to address prod mode.
> Add www to create studio url

- .github/workflows/jacktrip.yml
- docs/changelog.yml
- src/UdpDataProtocol.cpp
- src/UdpDataProtocol.h
- src/jacktrip_globals.cpp
- src/jacktrip_globals.h
- src/vs/virtualstudio.cpp
- src/vs/vsAudio.cpp
- src/vs/vsAudio.h
- win/meson.build
Fixed asio detection for about dialog on Windows
Bumping DSCP QoS from 46 to 56 to conform with WMM VO
Improved error handling when setting process and thread priorities on Windows
Bumped udp wait timeout from 30 to 50 ms because a buffer size of 1024 can easily cause 30 ms gaps between packets, at least for Windows computers
Removed the unused global gWaitCounter
> Adding support for Windows qWave (network traffic QoS)

- src/vs/Settings.qml
- src/vs/virtualstudio.cpp
- src/vs/vsAudio.cpp
- src/vs/vsAudio.h
I'm not all that happy with the 3-way "Queue Type" combo + slider, and wondering if it may be better to simplify it to a checkbox + slider. Please give this a try and compare to the latest in dev, and let me know which one you prefer.
> Slightly different take on advanced settings for latency

- .github/workflows/jacktrip.yml
Fixes https://github.com/jacktrip/jacktrip/issues/1349
> Make sure that classic mode support is included in OSX builds

- src/vs/virtualstudio.cpp
This is helpful when testing a copy of the web UI running locally
> Add cookies for localhost when running in test mode

- Dockerfile
Container push stage is failing in jacktriplabs repo, after adding libsamplerate
> Fix for missing cmake in dockerfile

- docs/changelog.yml
- src/AudioSocket.cpp
- src/jacktrip_globals.h
Commenting out some qDebug() statements in AudioSockets
> Updating version and changelog for 2.5.0 release

- .github/workflows/jacktrip.yml
- docs/changelog.yml
- src/jacktrip_globals.h
- src/vs/virtualstudio.cpp
- src/vs/vsServerInfo.cpp
- src/vs/vsServerInfo.h
Updating Qt in Mac builds from 6.2.6 to 6.2.11
Update version and changelog for 2.5.1 release
> Ensure that studio data is fresh before connecting

- CMakeLists.txt
From @yurivict
Fixes https://github.com/jacktrip/jacktrip/issues/1381
> Fix for building with cmake and vs mode

- meson.build
I think it works ok with system and subproject after this change
> Fix for -Dlibsamplerate=disabled

- externals/oscpp/include/oscpp/detail/endian.hpp
Fixes: https://github.com/jacktrip/jacktrip/issues/1404
> Add support for Linux on aarch64 and armv7

- .github/workflows/jacktrip.yml
- win/qt6-noguids.wxs
- win/qt6.wxs
This reverts commit 3c6af6869e57e92d1b393ad226221d343d4752b7.
> Revert "Temporarily reverting qt 6.8 upgrade for another 2.5.x release"

- src/vs/vsAudio.cpp
Apple Inc.: iPhone (38) Microphone
> Attempting to blacklist more iPhone microphones

- .github/workflows/jacktrip.yml
- docs/Build/Mac.md
- docs/Build/Windows.md
- docs/changelog.yml
- meson.build
- src/jacktrip_globals.h
- src/vs/CreateStudio.qml
- src/vs/WebEngine.qml
- src/vs/WebView.qml
- src/vs/virtualstudio.cpp
- src/vs/virtualstudio.h
Enable persistent cookies, cache and local storage in WebEngine
Cleanup for how WebEngine auth cookies are being set
Use static qt build when creating VST3 plugin on OSX
Update to Qt 6.8.3
Update to VST3SDK to 3.7.13
> Reworking webengine configuration

- src/vs/CreateStudio.qml
- src/vs/ScreenShareModal.qml
- src/vs/WebEngine.qml
- src/vs/virtualstudio.cpp
- src/vs/vs.qrc
Also moving WebEngine settings to QML since changing them in C++ doesn't work
> Adding modal to select what screen or window you would like to share

- .github/workflows/jacktrip.yml
- src/vs/ChangeDevices.qml
Adding AUv2 component to MacOS application zip file
> Fixing some issues with auto button for audio quality slider

- linux/Dockerfile.build
- src/main.cpp
https://github.com/jacktrip/jacktrip/security/advisories/GHSA-9vv9-3x8p-fxf2
Also: Fix linux docker build file for archival of debian buster
> Refuse to run if DYLD_INSERT_LIBRARIES is set on OSX

- linux/README.md
- src/vs/virtualstudio.cpp
Improving error message when connection to studio is lost
> Added missing libqt6quickdialogs2-6 dependency for Debian/Ubuntu
